In [24]:
# initialize project:
using Pkg; Pkg.activate("./env");;

# Find current path
CURRENT = pwd(); LIB_PATH = joinpath(CURRENT,"lib");

# include auxilliary functions:
for file in readdir(LIB_PATH); include(joinpath(LIB_PATH,file)); end;

  Activating project at `~/GitHub/ClassicalLambda/env`


# Introduction and background:
Following the notation and convention of **arXiv:2312.10734**, we can model a system of $n$-qubits by a Hilbert space $\mathcal{H} = (\mathbb{C}^2)^{\otimes n}$. Hermitian operators $\text{Herm}(\mathcal{H})$ form a real vector space with Hilbert-Schmidt inner product $\langle A,B \rangle = \text{Tr}(AB)$ for $A,B\in\text{Herm}(\mathcal{H})$. Pauli observables $T_a$ ($a\in E_n$) form an orthogonal basis for the space of Hermitian matrices so that any Hermitian matrix $X$ we have

$$A = \sum_{a\in E_n}\alpha_a T_a~,$$

where the $\alpha_a\in\mathbb{R}$ can be interpreted as the expectation value of the Pauli observable $T_a$ via the Born rule:

$$\langle A,T_a \rangle = \text{Tr}(AT_a) = \alpha_a~.$$

Thus any $A\in\text{Herm}(\mathcal{H})$ can be fully characterized by a vector $\alpha \in\mathbb{R}^{4^n}$ whose components are $\alpha_a$. For Hermitian matrices with $\text{Tr}(A) = 1$ this sets $\alpha_0 = 1$ and we can work concretely in a real Euclidean space $\mathbb{R}^{4^n-1}$.

# Stabilizer polytopes and $\Lambda$ polytopes

The single-qubit Pauli operators are given by

$$X = \begin{bmatrix} 0 &  1\\ 1 &  0\end{bmatrix},\quad%
  Y = \begin{bmatrix} 0 & -i\\ i &  0\end{bmatrix},\quad%
  Z = \begin{bmatrix} 1 &  0\\ 0 &  -1\end{bmatrix}.$$

  For $n$-qubits a Hermitian matrix $P$ is called a Pauli operator if it is of the form

  $$P = A_1\otimes\cdots\otimes A_n\quad\text{where}\quad A_i\in \{I,X,Y,Z\}.$$

  The $n$-qubit Pauli group $P_n$ consists of all Pauli operators $i^\zeta P$ where $\zeta \in \mathbb{Z}_4$. The $n$-qubit Clifford group is defined as $\text{Cl}_n = P_n/\left \langle e^{i\theta}I~:~\theta\in \mathbb{R}\right\rangle$. A stabilizer group $S\subset P_n$ is an abelian subgroup of the Pauli group in which all elements square to the identity. We call a stabilizer group maximal if the number of independent Pauli elements is $n$. Here we deal only with maximal stabilizer groups. By definition, for each stabilizer group there exists some $\left | \psi_S\right \rangle\in \mathcal{H}$ such that $s\left | \psi_S\right \rangle = \left | \psi_S\right \rangle$ for all $s\in S$.

The projector $\Pi_S$ onto the mutual $+1$ eigenspace of each $s\in S$ is given by:

$$\Pi_S = \frac{1}{2^n}\sum_{s\in S} s~.$$

Let $\mathcal{S}_n$ be the set of $n$-qubit stabilizer groups. The stabilizer polytope $\text{SP}_n$ is defined as the convex hull of stabilizer states. Its polar dual $\Lambda_n := \text{SP}_n^\ast$ can be formally defined as

$$\Lambda_n := \left \{ A\in \text{Herm}(\mathcal{H})~:~\text{Tr}(A) = 1,~\text{Tr}(\Pi_SA)\geq 0~\forall S\in \mathcal{S}_n \right\}~.$$

## $\mathbf{2}$-qubits

Consider the $2$-qubit case. We call a Pauli operator *local* if it is of the form $A\otimes I$ or $I\otimes A$, where $A\in \{X,Y,Z\}$ is a single qubit Pauli matrix; otherwise we call it *nonlocal*. Let us organize our Pauli coordinates into local-nonlocal parts, such that $\alpha = ({x}^\ell,{x}^{n\ell})\in \mathbb{R}^{15}$, where:

$${x}^\ell = \left(x_{X_1},x_{Y_1},x_{Z_1},x_{X_2},x_{Y_2},x_{Z_2} \right)\in \mathbb{R}^6$$
$${x}^{n\ell} = \left(x_{XX},x_{XY},x_{XZ},x_{YX},x_{YY},x_{YZ},x_{ZX},x_{ZY},x_{ZZ} \right)\in\mathbb{R}^9.$$

**Convention**: we index our coordinates by $a = 1,\cdots,6$ for the local part while $a = 7,\cdots,15$ the nonlocal coordinates. (If the homogenizing coordinate $\alpha_0 = 1$ is included then this offset by one so that the local coordinates have index $a = 2,\cdots,7$, while the nonlocal coordinates have index $a = 8,\cdots,16$.)

For $2$-qubits there are (up to signs) $15$ stabilizer groups. If a stabilizer group contains a local Pauli then it is called local; otherwise it is called nonlocal. There are $9$ local stabilizer groups and $6$ nonlocal ones. Disregarding the signs of the Pauli operators, the stabilizer groups consist of the Pauli operators:

\begin{align}
{\textbf{Local}:}\quad\quad & \{I,XI,IX,XX\}, \{I,XI,IY,XY\}, \{I,XI,IZ,XZ\},\notag\\
                                 & \{I,YI,IX,YX\}, \{I,YI,IY,YY\}, \{I,YI,IZ,YZ\},\notag\\
                                 & \{I,ZI,IX,ZX\}, \{I,ZI,IY,ZY\}, \{I,ZI,IZ,ZZ\},\notag\\
{\textbf{Nonlocal}:}\quad\quad & \{I,XY,YX,ZZ\}, \{I,YZ,ZY,XX\}, \{I,ZX,XZ,YY\},\notag\\
                                 & \{I,XY,ZX,YZ\}, \{I,YX,XZ,ZY\}, \{I,ZZ,YY,XX\}.\notag
\end{align}

In all but the last row, this products of Pauli operators multiplies to the $I$ whereas for the last row they multiply to $-I$.  For instance, we have

$$I\cdot XY \cdot YZ \cdot ZZ = I\quad \text{while} \quad I\cdot XX \cdot ZZ \cdot YY = - I~.$$



# $\mathbf{2}$-qubit $\Lambda$ polytope



## Stabilizer groups

In [ ]:
# Pauli operators are labeled according to: X1,Y1,Z1,X2,Y2,Z2,XX,XY,XZ,...,ZY,ZZ:
X1 = [[i,[1,1]] for i in 1:15];

In [27]:
# Generate arrays corresponding to local stabilizer groups:
stabilizer_groups_local = [[1,4,7],[1,5,8],[1,6,9],
                    [2,4,10],[2,5,11],[2,6,12],
                    [3,4,13],[3,5,14],[3,6,15]];

# Generate arrays corresponding to local stabilizer groups:                   
stabilizer_groups_nonlocal = [[8,10,15],[12,14,7],[13,9,11],
                    [8,13,12],[10,9,14],[15,11,7]];

# All 2-qubit stabilizer groups:
stabilizer_groups = vcat(stabilizer_groups_local,stabilizer_groups_nonlocal);

In [11]:
# Some sets have the property that multiplying all the Pauli operators A*B*AB = (-1)Identity.
T = [[13,1,2],[14,1,2],[15,1,2]];

In [12]:
# Create the polytope generated by
L2 = two_dimensional_distributions(X1,X2,"EDGE",T);

In [13]:
# extract facets:
A = L2.INEQUALITIES;
# local/nonlocal facets
A_l = A[1:36,:]; A_nl = A[37:60,:];

In [426]:
# representative_vertices
L2_rep = representative_vertices(L2)[[3,1,4,8,6,2,5,7],:]

pm::Matrix<pm::Rational>
1 -1 0 -1 0 0 0 0 0 0 1 1 -1 0 0 0
1 -1 -1 -1 1 0 0 -1 0 0 -1 0 0 -1 0 0
1 -1 1/2 0 0 1 -1/2 0 -1 1/2 -1/2 1/2 0 0 0 1/2
1 -1/2 -1/2 -1/2 1/2 0 0 0 -1/2 1/2 0 1/2 1/2 0 -1/2 -1/2
1 -1/2 0 -1/2 0 0 0 -1/2 -1/2 -1/2 -1 0 1 1/2 -1/2 1/2
1 -1 0 -1/2 1/2 1/2 1/2 -1/2 -1/2 -1/2 -1/2 1/2 1/2 0 -1 0
1 -2/3 -1/3 0 2/3 1/3 0 -1 -2/3 -1/3 -2/3 1/3 2/3 1/3 -2/3 1/3
1 1/2 -1/2 3/4 1/4 -3/4 -3/4 -1/4 -3/4 -1/4 1/4 1/4 3/4 1/2 -1/2 -1/2


In [437]:
L2_orbits = vertex_orbit(L2)[[3,1,4,8,6,2,5,7]];

In [14]:
# projection to nonlocal coordinates:
nonlocal_idx = [1,8,9,10,11,12,13,14,15,16];

# Nonsignaling polytope

In [15]:
# create polytope
NS232 = pm.polytope.Polytope(INEQUALITIES=A_l);

In [16]:
# Find orbits of vertices:
NS232_orbits = vertex_orbit(NS232);
det_idx = findall(y->length(y)==64,NS232_orbits)[1];
D = NS232.VERTICES[NS232_orbits[det_idx],:];

In [17]:
# Bell polytope
C = pm.polytope.Polytope(POINTS = D)
B = Matrix{Rational{Int64}}(C.FACETS);

# Nonlocal polytopes

## $\overline{CL}$

In [18]:
# Projection of C:
bar_D = D[:,nonlocal_idx];
Cb = pm.polytope.Polytope(POINTS = bar_D);
# Facets:
H2 = Matrix{Rational{Int64}}(Cb.FACETS);
# Vertices:
V2 = Matrix{Rational{Int64}}(Cb.VERTICES);

In [19]:
# Orbits of Cb facets:
h2 = facets_orbit(Cb);
# CHSH facets:
h2_prime = h2[1]; H2_prime = H2[h2_prime,:];

## $\mathbf{\text{MP}_1}$

In [20]:
# Nonlocal Lambda2 polytope:
L2_nl = two_dimensional_distributions(X1,X2[10:15],"EDGE",T);
# MP1 as projection of L2_nl:
MP1 = pm.polytope.Polytope(POINTS = L2_nl.VERTICES[:,nonlocal_idx]);
# Facets:
H1 = Matrix{Rational{Int64}}(MP1.FACETS);
# Vertices:
V1 = Matrix{Rational{Int64}}(MP1.VERTICES);

In [21]:
# Orbits of Cb facets:
v1 = vertex_orbit(MP1);
# CHSH facets:
v1_prime = v1[1]; V1_prime = V1[v1_prime,:];

## $\mathbf{\overline{\text{MP}}}$

In [22]:
# define mp_tilde (now called mp_bar)
H12 = vcat(H1,H2);
MPb = pm.polytope.Polytope(INEQUALITIES = H12);

In [23]:
# representative vertices of mp_tilde:
MPb_rep = representative_vertices(MPb)

pm::Matrix<pm::Rational>
1 -1 -1 -1 0 0 0 0 0 0
1 -1/2 -1 1/2 -1/2 0 -1/2 -1/2 0 1/2
1 0 -1 0 -1 0 0 0 0 1
1 -1/3 -2/3 -2/3 -2/3 1/3 -1/3 -2/3 -1/3 1/3
1 -2/3 2/3 0 2/3 0 2/3 -1/3 -1/3 1/3
1 -3/5 1/5 -3/5 -1/5 3/5 3/5 -3/5 -3/5 1/5
1 -1 0 1/3 1/3 2/3 -1/3 0 1/3 2/3
1 -1 1/3 0 -1/3 -1/3 -2/3 0 2/3 -1/3
1 -1 1/2 0 0 1/2 0 1/2 0 1/2
1 -1/2 0 -3/4 1/2 -1/2 -1/4 1/4 3/4 -1/2


# Canonical vertex, neighbor, and $\mathbf{2}$-neighbors

### Canonical vertex $\mathbf{v}$ of $\mathbf{\text{MP}_1}$

In [5]:
v = Vector{Rational{Int64}}([1,1,1,0,1,-1,0,0,0,1]);

The canonical $\bar T_2$ vertex $v$ violates precisely one CHSH facet $h_v$ that is *dual* to it:

In [55]:
hv_idx = violated_inequality(v,H2); hv = H2[hv_idx,:]

1×10 Matrix{Rational{Int64}}:
 2//1  -1//1  -1//1  0//1  -1//1  1//1  0//1  0//1  0//1  0//1

### Canonical neighbor $\mathbf{v^\prime}$  of $\mathbf{v}$ in $\mathbf{\text{MP}_1}$

In [8]:
v_prime = Vector{Rational{Int64}}([1,1,0,0,0,-1,-1,0,-1,1]);

Joint rank of ${v}$ and ${v^\prime}$ in ${\text{MP}_1}$:

In [27]:
joint_rank(v,v_prime,H1)

8

Inner product with canonical facet $h_v$. All neighbors $v^\prime$ of $v$ have $h_v\cdot v^\prime = 0$. 

In [58]:
hv*v_prime

1-element Vector{Rational{Int64}}:
 0//1

### Canonical $\mathbf{2}$-neighbors $\mathbf{w_0}$, $\mathbf{w_1}$, $\mathbf{w_2}$, $\mathbf{w_3}$  of $\mathbf{v}$ in $\mathbf{\text{MP}_1}$

In [29]:
w0 = Vector{Rational{Int64}}([1,1,-1,0,0,0,-1,-1,-1,0]);
w1 = Vector{Rational{Int64}}([1,1,-1,0,-1,-1,0,0,0,1]);
w2 = Vector{Rational{Int64}}([1,0,-1,0,0,-1,0,0,-1,0]);
w3 = Vector{Rational{Int64}}([1,0,-1,0,-1,0,-1,-1,0,1]);

In [30]:
W = Matrix([w0 w1 w2 w3])

10×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1   0//1   0//1
 -1//1  -1//1  -1//1  -1//1
  0//1   0//1   0//1   0//1
  0//1  -1//1   0//1  -1//1
  0//1  -1//1  -1//1   0//1
 -1//1   0//1   0//1  -1//1
 -1//1   0//1   0//1  -1//1
 -1//1   0//1  -1//1   0//1
  0//1   1//1   0//1   1//1

Joints ranks of $w_i$ ($i =0,\cdots,3$) with $v$ in ${\text{MP}_1}$:

In [35]:
for i in 1:4; println("Joint rank of v with w"*string(i)*" is: ", joint_rank(v,W[:,i],H1)); end;

Joint rank of v with w1 is: 7
Joint rank of v with w2 is: 6
Joint rank of v with w3 is: 6
Joint rank of v with w4 is: 6


Inner product with canonical facet $h_v$. All $2$-neighbors $w_i$ of $v$ have $h_v\cdot v^\prime > 0$. 

In [59]:
for i in 1:4; println("Inner product hv with w"*string(i)*" is: ", hv*W[:,i]); end;

Inner product hv with w1 is: Rational{Int64}[2//1]
Inner product hv with w2 is: Rational{Int64}[2//1]
Inner product hv with w3 is: Rational{Int64}[2//1]
Inner product hv with w4 is: Rational{Int64}[4//1]


# Generating vertices of $\mathbf{\overline{\text{MP}}}$

## Increasing joint rank

We look for common tight CHSH facets between $v$ and $w_i$.

In [76]:
# initialize empty Vector{Any}:
H2int = []; Zv = tight_inequalities(v,H2_prime);
for i in 1:4
    Zwi = tight_inequalities(W[:,i],H2_prime);
    Zint = collect(intersect(Set(Zv),Set(Zwi)));
    push!(H2int,H2_prime[Zint,:]);
end

In [70]:
H2_int[1]

4×10 Matrix{Rational{Int64}}:
 2//1   0//1  0//1   0//1   0//1  1//1  1//1  0//1  1//1  -1//1
 2//1   0//1  0//1   0//1  -1//1  1//1  0//1  1//1  1//1   0//1
 2//1  -1//1  0//1  -1//1   0//1  0//1  0//1  1//1  0//1  -1//1
 2//1  -1//1  0//1  -1//1  -1//1  0//1  1//1  0//1  0//1   0//1

In [71]:
H2_int[2]

4×10 Matrix{Rational{Int64}}:
 2//1  -1//1  0//1   1//1  0//1  0//1   0//1  -1//1   0//1  -1//1
 2//1   0//1  0//1   0//1  0//1  1//1   1//1   0//1   1//1  -1//1
 2//1   0//1  0//1   0//1  0//1  1//1  -1//1   0//1  -1//1  -1//1
 2//1  -1//1  0//1  -1//1  0//1  0//1   0//1   1//1   0//1  -1//1

In [73]:
H2_int[3]

2×10 Matrix{Rational{Int64}}:
 2//1  0//1  0//1  0//1   0//1  1//1  1//1  0//1  1//1  -1//1
 2//1  0//1  0//1  0//1  -1//1  1//1  0//1  1//1  1//1   0//1

In [74]:
H2_int[4]

2×10 Matrix{Rational{Int64}}:
 2//1   0//1  0//1   0//1  0//1  1//1  1//1  0//1  1//1  -1//1
 2//1  -1//1  0//1  -1//1  0//1  0//1  0//1  1//1  0//1  -1//1

Compute joint rank of $v$ and $w_i$ with facets of $\text{MP}_1$ together with CHSH facets of $\bar C$

In [91]:
Zv = tight_inequalities(v,H1);
for i in 1:4
    # find common tight inequalities in H1:
    Zwi = tight_inequalities(W[:,i],H1);
    Zint = collect(intersect(Set(Zv),Set(Zwi)));
    H1Z = H1[Zint,:];
    # Concatenate tight H1 and H2 inequalities:
    H12Z = vcat(H1Z,H2_int[i]);
    println("Updated joint rank of v with w"*string(i)*" is: ", rank(H12Z))
end

Updated joint rank of v with w1 is: 8
Updated joint rank of v with w2 is: 8
Updated joint rank of v with w3 is: 8
Updated joint rank of v with w4 is: 8


## Generate vertices using DD method

### function: new_vertex

Given the cone $P_0^\ast$ of a full-dimensional polytope $P_0\subseteq \mathbb{R}^d$ and a hyperplane $h\cdot x = 0$, the DD method guarantees that for all pairs of adjacent extreme rays $v,v^\prime\in P_0^\ast$ (i.e., joint rank is $d-2$) such that $h\cdot v < 0$ and $h\cdot v^\prime > 0$ that the positive sum of these points given by

$$u = pv-(1-p)v^\prime\quad\text{where}\quad p = \frac{1}{1-\frac{h\cdot v}{h\cdot v^\prime}}\in [0,1]$$

is an extreme ray of the new cone $P_1^\ast$, which is obtained from $P^\ast_0$ by the insertion of the new inequality $h\cdot x \geq 0$.

**Input:** Vector: v_minus: violating vector ($d\times 1$)

**Input:** Vector: v_plus: satisfying vector ($d\times 1$)

**Input:** Vector: h: facet vector ($1\times d$)

**Output:** Vector: new_vertex ($d\times 1$)

In [ ]:
function new_vertex(v_minus,v_plus,h)
    d = size(v_minus)[1];
    if size(h)[1] == d
        a = (transpose(h)*v_minus)[1];
        b = (transpose(h)*v_plus)[1];
    else
        a = ((h)*v_minus)[1];
        b = ((h)*v_plus)[1];
    end
    p = b/(b-a);
    if p < 0
        return "No vertex possible"
    elseif p == 0
        return "No new vertex possible"
    else
        return p*v_minus+(1-p)*v_plus
    end
end

In [155]:
U = zeros(Rational{Int64},10,4);
for i in 1:4; U[:,i] .= new_vertex(v,W[:,i],hv); end; U

10×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1   1//2   2//3
  0//1   0//1   0//1   1//3
  0//1   0//1   0//1   0//1
  1//2   0//1   1//2   1//3
 -1//2  -1//1  -1//1  -2//3
 -1//2   0//1   0//1  -1//3
 -1//2   0//1   0//1  -1//3
 -1//2   0//1  -1//2   0//1
  1//2   1//1   1//2   1//1

# Lifting


## General Lifting

Let us decompose $\mathbb{R}^{15} = \mathbb{R}^6\oplus\mathbb{R}^9$ so that $X = (x,\bar x)$, where $x\in \mathbb{R}^6$ and $\bar x \in \mathbb{R}^9$. The $H$-representation of $\Lambda_2$ is given by

$$\Lambda_2 = \left\{X \in \mathbb{R}^{15}~|~MX\geq -\mathbb{1}_{60\times 1}\right\}.$$

We can similarly decompose the matrix $M\in \mathbb{R}^{60\times 15}$ into local and nonlocal parts:

$$M = \begin{pmatrix} M^{l} & M^{(nl)}\\ \mathbb{0} & \bar M^{(nl)}\end{pmatrix}~.$$

Any point $\bar x \in \text{MP}_1 \subset \mathbb{R}^9$ satisfies the inequalities $\bar M^{(nl)}\bar x \geq -\mathbb{1}_{24\times 1}.$ For fixed $\bar x \in \text{MP}_1$ we wish to lift this to a point $ X = ( x, \bar x) \in \Lambda_2$. For this to happen the coordinates $ x \in \mathbb{R}^6$ must satisfy

$$M^{(l)} x + \bar M^{(nl)}\bar x \geq -\mathbb{1}_{36\times 1}.$$

Since $\bar x$ is given and $\bar M^{(nl)}$ is known this amounts to $M^{(l)} x \geq -\mathbb{1}_{36\times 1} -  \bar M^{(nl)}\bar x$. The space of such $x\in \mathbb{R}^6$ satisfying these inequalities itself forms a convex polytope that we call $\tilde{\text{MP}}_{\bar x}$.

In [160]:
# local inequalities:
S = [i for i in 1:36];
# nonlocal coordinates
s = [i for i in 8:16];

In [468]:
# local/total generating matrix:
M_loc = Matrix{Rational{Int64}}(A_l);
# Lambda2/total generating matrix
M = Matrix{Rational{Int64}}(A);

### $\mathbf{\widetilde{\text{MP}}_{u_i}}$

In [493]:
for i in 1:4
    # generate polytope of lifts:
    MP_ui = lift_mp1(U[2:end,i],A,S,s);
    
    # display vertices:
    println("For vertex u"*string(i-1)*" the polytope of lifts has "*string(MP_ui.N_VERTICES)*" total vertices. Its representative vertices are: \n ")
    display(representative_vertices(MP_ui));
    println("_______________________________________________________ \n ")
    
    # run through all vertices of MP_ui
    for j in 1:size(MP_ui.VERTICES)[1]
        # vertex of MP_ui:
        v = Vector{Rational{Int64}}(MP_ui.VERTICES[j,:])
        
        # compute local rank:
        Zloc = tight_inequalities(v,M_loc);
        rloc = rank(M_loc[Zloc,:]);
        
        # compute total rank:
        Z = tight_inequalities(v,M);
        r = rank(M[Z,:]);
        
        if r == 15
            v_idx = findall(y->y==v,L2_array)[1];
            for t in 1:8
                if v_idx in L2_orbits[t]
                    println("The vertex below is number "*string(v_idx)*" and type "*string(t)*" in Lambda2: ")
                    println(v, "\n ")
                    println("has local rank: ", rloc)
                    println("has total rank: ", r, " \n ")
                    println("______________________\n")
                end
            end
        end
    end
    println("_______________________________________________________\n ")
end

For vertex u0 the polytope of lifts has 22 total vertices. Its representative vertices are: 
 


pm::Matrix<pm::Rational>
1 -1 -1/2 1/2 -1 0 0 1 0 0 1/2 -1/2 -1/2 -1/2 -1/2 1/2
1 -1/2 0 0 -1/2 -1/2 -1/2 1 0 0 1/2 -1/2 -1/2 -1/2 -1/2 1/2
1 -1/2 0 0 -1/2 -1/2 1/2 1 0 0 1/2 -1/2 -1/2 -1/2 -1/2 1/2
1 0 1/2 -1/2 0 0 0 1 0 0 1/2 -1/2 -1/2 -1/2 -1/2 1/2


_______________________________________________________ 
 
The vertex below is number 18344 and type 6 in Lambda2: 
Rational{Int64}[1//1, -1//2, 0//1, 1//1, -1//2, -1//2, 1//2, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
has local rank: 11
has total rank: 15 
 
______________________

The vertex below is number 9729 and type 5 in Lambda2: 
Rational{Int64}[1//1, 0//1, 1//2, 1//2, 0//1, -1//1, 0//1, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
has local rank: 10
has total rank: 15 
 
______________________

The vertex below is number 12183 and type 6 in Lambda2: 
Rational{Int64}[1//1, -1//2, -1//1, 0//1, -1//2, 1//2, 1//2, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
has local rank: 11
has total rank: 15 
 
______________________

The vertex below is number 9561 and type 6 in Lambda2: 
Rational{Int64}[1//1, 1//2, 0//1, -1//1, 1//2, 1//2, -1//2, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
has local rank: 11
has total rank: 15 


pm::Matrix<pm::Rational>
1 -1 0 0 -1 0 0 1 0 0 0 -1 0 0 0 1
1 -1/2 1/2 -1/2 -1/2 -1/2 -1/2 1 0 0 0 -1 0 0 0 1


_______________________________________________________ 
 
The vertex below is number 17985 and type 3 in Lambda2: 
Rational{Int64}[1//1, -1//2, 1//2, -1//2, -1//2, -1//2, -1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1]
 
has local rank: 12
has total rank: 15 
 
______________________

The vertex below is number 18350 and type 3 in Lambda2: 
Rational{Int64}[1//1, -1//2, 1//2, 1//2, -1//2, -1//2, 1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1]
 
has local rank: 12
has total rank: 15 
 
______________________

The vertex below is number 15364 and type 3 in Lambda2: 
Rational{Int64}[1//1, -1//2, -1//2, 1//2, -1//2, 1//2, 1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1]
 
has local rank: 12
has total rank: 15 
 
______________________

The vertex below is number 15077 and type 3 in Lambda2: 
Rational{Int64}[1//1, 1//2, -1//2, -1//2, 1//2, 1//2, -1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1]
 
has local rank: 12
has total rank: 15 
 
___

pm::Matrix<pm::Rational>
1 -1 0 -1/2 -1/2 0 0 1/2 0 0 1/2 -1 0 0 -1/2 1/2
1 -1 0 1/2 -1/2 0 0 1/2 0 0 1/2 -1 0 0 -1/2 1/2
1 -1/2 -1/2 0 -1 1/2 -1/2 1/2 0 0 1/2 -1 0 0 -1/2 1/2
1 -1/2 1/2 0 0 -1/2 1/2 1/2 0 0 1/2 -1 0 0 -1/2 1/2
1 -1/2 -1/2 0 0 1/2 -1/2 1/2 0 0 1/2 -1 0 0 -1/2 1/2
1 0 0 -1/2 -1/2 0 0 1/2 0 0 1/2 -1 0 0 -1/2 1/2


_______________________________________________________ 
 
The vertex below is number 3013 and type 5 in Lambda2: 
Rational{Int64}[1//1, -1//2, -1//2, 0//1, -1//1, 1//2, 1//2, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2]
 
has local rank: 11
has total rank: 15 
 
______________________

The vertex below is number 18353 and type 5 in Lambda2: 
Rational{Int64}[1//1, -1//2, 1//2, 1//1, 0//1, -1//2, 1//2, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2]
 
has local rank: 11
has total rank: 15 
 
______________________

The vertex below is number 12707 and type 5 in Lambda2: 
Rational{Int64}[1//1, 1//2, 1//2, 0//1, 1//1, -1//2, -1//2, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2]
 
has local rank: 11
has total rank: 15 
 
______________________

The vertex below is number 11897 and type 3 in Lambda2: 
Rational{Int64}[1//1, 0//1, -1//1, -1//2, -1//2, 1//1, 0//1, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2]
 
has local rank: 10
has total rank: 15 
 
____

pm::Matrix<pm::Rational>
1 -1 0 0 -2/3 -1/3 0 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 -2/3 -1/3 1/3 -1 0 1/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 -2/3 1/3 -1/3 -1/3 -2/3 -1/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 -1/3 -2/3 2/3 -2/3 1/3 2/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 -1/3 -2/3 0 -2/3 1/3 0 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 -2/3 1/3 1/3 -1/3 0 1/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 -1/3 0 2/3 -2/3 1/3 2/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 1/3 0 -2/3 2/3 1/3 -2/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 0 1/3 -1 1/3 0 -1 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 -1/3 0 -2/3 0 -1/3 -2/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 0 1/3 1/3 -1/3 -2/3 1/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 2/3 1/3 1/3 1/3 0 1/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 -1/3 0 2/3 0 1/3 2/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 1/3 0 2/3 0 -1/3 2/3 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1
1 1/3 2/3 0 0 -1/3 0 2/3 1/3 0 1/3 -2/3 -1/3 -1/3 0 1


_______________________________________________________ 
 
The vertex below is number 14485 and type 7 in Lambda2: 
Rational{Int64}[1//1, -1//3, -2//3, 2//3, -2//3, 1//3, 2//3, 2//3, 1//3, 0//1, 1//3, -2//3, -1//3, -1//3, 0//1, 1//1]
 
has local rank: 10
has total rank: 15 
 
______________________

The vertex below is number 11606 and type 7 in Lambda2: 
Rational{Int64}[1//1, 1//3, 2//3, -2//3, 2//3, -1//3, -2//3, 2//3, 1//3, 0//1, 1//3, -2//3, -1//3, -1//3, 0//1, 1//1]
 
has local rank: 10
has total rank: 15 
 
______________________

_______________________________________________________
 


## Classical lift

In [249]:
# import functions:
include("convex_decomposition.jl");

In [312]:
cd_array = [];
for i in 1:4
    println("For vertex u"*string(i-1)*"\n")
    
    # compute decomposition of ui in terms of V2:
    delta_i, cd_i = convex_decomposition(U[:,i],H2,V2);
    
    # collect results:
    push!(cd_array,[delta_i,Matrix{Rational{Int64}}(cd_i.VERTICES)]);
    
    # print results:
    println("Vertices appearing in decomposition: \n");
    display(delta_i); println("\n ");
    println("Vertices of allowed convex combinations: \n ");
    display(cd_array[i][2]); println("\n ")
end

For vertex u0

Vertices appearing in decomposition: 



10×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1


 
Vertices of allowed convex combinations: 
 


1×5 Matrix{Rational{Int64}}:
 1//1  1//4  1//4  1//4  1//4


 
For vertex u1

Vertices appearing in decomposition: 



10×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1


 
Vertices of allowed convex combinations: 
 


1×5 Matrix{Rational{Int64}}:
 1//1  1//4  1//4  1//4  1//4


 
For vertex u2

Vertices appearing in decomposition: 



10×8 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1   1//1   1//1   1//1   1//1
  1//1   1//1   1//1   1//1  -1//1  -1//1   1//1  -1//1
  1//1  -1//1   1//1  -1//1   1//1   1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1  -1//1   1//1  -1//1   1//1
 -1//1   1//1  -1//1   1//1   1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1  -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1   1//1  -1//1  -1//1  -1//1
 -1//1  -1//1  -1//1   1//1   1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1  -1//1  -1//1   1//1  -1//1  -1//1
  1//1   1//1  -1//1   1//1   1//1   1//1  -1//1  -1//1


 
Vertices of allowed convex combinations: 
 


3×9 Matrix{Rational{Int64}}:
 1//1  0//1  1//4  1//4  1//4  1//4  0//1  0//1  0//1
 1//1  1//4  1//4  0//1  1//4  0//1  0//1  0//1  1//4
 1//1  1//4  0//1  0//1  1//4  0//1  1//4  1//4  0//1


 
For vertex u3

Vertices appearing in decomposition: 



10×6 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1   1//1   1//1
  1//1   1//1   1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1  -1//1   1//1
 -1//1   1//1  -1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1   1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1  -1//1  -1//1
 -1//1   1//1   1//1  -1//1  -1//1   1//1
  1//1   1//1   1//1   1//1   1//1   1//1


 
Vertices of allowed convex combinations: 
 


1×7 Matrix{Rational{Int64}}:
 1//1  1//6  1//6  1//6  1//6  1//6  1//6

### Lift of $\mathbf{\overline{\text{MP}}}$ vertices

In [301]:
# Matrix of deterministic vertices:
D_array = Matrix{Rational{Int64}}(D);

In [416]:
# array of L2 vertices: useful for searching:
L2_array = polymake_to_array(L2.VERTICES);

In [497]:
classical_vertices = [[ ] for i in 1:4];

# Lift each vertex ui of MPb:
for i in 1:4
    println("Vertex u"*string(i-1)*" \n ")
    preimages_array = [];
    
    # find preimages of Cb vertices:
    for j in 1:size(cd_array[i][1])[2]
        
        # define vertex of Cb:
        delta = cd_array[i][1][2:end,j];
        
        # find elements of D that project to delta
        preimage_idx = [k for k in 1:size(D_array)[1] if (D_array[k,8:16] == delta)]
        
        # create matrix of preimages:
        preimage = transpose(Matrix{Rational{Int64}}(D[preimage_idx,:]));
        push!(preimages_array,preimage);
    end
    
    
    # perform convex combinations:
    for k in 1:size(cd_array[i][2])[1]
        vertices_in_decomposition = findall(y->y != 0,cd_array[i][2][k,2:end])
        
        # number of combinations:
        bit_strings = all_dit_strings(2,length(vertices_in_decomposition));
        for x in bit_strings
            # preimages used:
            subset_of_preimages = preimages_array[vertices_in_decomposition]
            
            # initialize matrix of vertices in decomposition:
            R = subset_of_preimages[1][:,x[1]+1];
            for j in 2:length(subset_of_preimages)
                R = hcat(R,subset_of_preimages[j][:,(x[j]+1)])
            end
            
            # parameters of convex mixture
            mixture = (cd_array[i][2][k,2:end])[vertices_in_decomposition]
            # classical distribution:
            v = R*mixture;
            # rank of distribution:
            Zv = tight_inequalities(v, M); rank_Mv = rank(M[Zv,:]);
            if rank_Mv == 15
                v_idx = findall(y->y == v,L2_array)[1]
                for t in 1:8
                    if v_idx in L2_orbits[t]
                        pair = [v,t];
                        if (pair in classical_vertices[i]) == false
                            push!(classical_vertices[i],pair)
                            println("Using deterministic vertices: \n ");
                            display(R)
                            println("'beta' values: ",[(R[8,c]*R[12,c]*R[16,c]) for c in 1:size(R)[2]],"\n")
                            println("and convex mixture \n ")
                            display((mixture)); println(" \n ")
                            println("we obtain vertex "*string(v_idx)*" of type "*string(t)*" \n ")
                            println(v, " \n ")
                            println("__________________ \n ")
                        end
                    end
                end
            end
        end
        println("______________________________________________________________ \n ")
    end
    
    # remove redundant vertices:
    classical_vertices[i] = collect(Set(classical_vertices[i]));
end

Vertex u0 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 18344 of type 6 
 
Rational{Int64}[1//1, -1//2, 0//1, 1//1, -1//2, -1//2, 1//2, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1  -1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1  -1//1
  1//1   1//1  -1//1   1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 12183 of type 6 
 
Rational{Int64}[1//1, -1//2, -1//1, 0//1, -1//2, 1//2, 1//2, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1   1//1
  1//1  -1//1  -1//1  -1//1
 -1//1   1//1  -1//1   1//1
  1//1   1//1   1//1   1//1
  1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 6124 of type 5 
 
Rational{Int64}[1//1, 0//1, -1//2, -1//2, 0//1, 1//1, 0//1, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
  1//1   1//1   1//1  -1//1
 -1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 9729 of type 5 
 
Rational{Int64}[1//1, 0//1, 1//2, 1//2, 0//1, -1//1, 0//1, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1   1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1  -1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 4845 of type 6 
 
Rational{Int64}[1//1, 1//2, 1//1, 0//1, 1//2, -1//2, -1//2, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1  -1//1   1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 9561 of type 6 
 
Rational{Int64}[1//1, 1//2, 0//1, -1//1, 1//2, 1//2, -1//2, 1//1, 0//1, 0//1, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2] 
 
__________________ 
 
______________________________________________________________ 
 
Vertex u1 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
  1//1  -1//1   1//1   1//1
  1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1  -1//1   1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 18350 of type 3 
 
Rational{Int64}[1//1, -1//2, 1//2, 1//2, -1//2, -1//2, 1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1   1//1   1//1  -1//1
 -1//1  -1//1   1//1  -1//1
 -1//1   1//1   1//1   1//1
  1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 15364 of type 3 
 
Rational{Int64}[1//1, -1//2, -1//2, 1//2, -1//2, 1//2, 1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1  -1//1
  1//1  -1//1  -1//1  -1//1
 -1//1   1//1  -1//1  -1//1
 -1//1  -1//1  -1//1   1//1
  1//1  -1//1  -1//1  -1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 17985 of type 3 
 
Rational{Int64}[1//1, -1//2, 1//2, -1//2, -1//2, -1//2, -1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1   1//1   1//1   1//1
  1//1   1//1  -1//1   1//1
  1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1   1//1
 -1//1  -1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 12722 of type 3 
 
Rational{Int64}[1//1, 1//2, 1//2, 1//2, 1//2, -1//2, 1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1  -1//1  -1//1  -1//1
 -1//1  -1//1   1//1  -1//1
 -1//1   1//1  -1//1  -1//1
  1//1  -1//1  -1//1  -1//1
  1//1   1//1  -1//1   1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 16710 of type 3 
 
Rational{Int64}[1//1, -1//2, -1//2, -1//2, -1//2, 1//2, -1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
 -1//1   1//1   1//1   1//1
  1//1  -1//1   1//1   1//1
  1//1   1//1   1//1  -1//1
 -1//1   1//1   1//1   1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 10671 of type 3 
 
Rational{Int64}[1//1, 1//2, -1//2, 1//2, 1//2, 1//2, 1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
  1//1   1//1  -1//1   1//1
  1//1  -1//1  -1//1  -1//1
 -1//1  -1//1  -1//1   1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 9815 of type 3 
 
Rational{Int64}[1//1, 1//2, 1//2, -1//2, 1//2, -1//2, -1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1   1//1  -1//1
 -1//1   1//1  -1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1  -1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 15077 of type 3 
 
Rational{Int64}[1//1, 1//2, -1//2, -1//2, 1//2, 1//2, -1//2, 1//1, 0//1, 0//1, 0//1, -1//1, 0//1, 0//1, 0//1, 1//1] 
 
__________________ 
 
______________________________________________________________ 
 
Vertex u2 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1  -1//1   1//1  -1//1
 -1//1   1//1   1//1   1//1
  1//1   1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1
  1//1   1//1   1//1  -1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 18353 of type 5 
 
Rational{Int64}[1//1, -1//2, 1//2, 1//1, 0//1, -1//2, 1//2, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1  -1//1  -1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1   1//1
  1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1  -1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 11897 of type 3 
 
Rational{Int64}[1//1, 0//1, -1//1, -1//2, -1//2, 1//1, 0//1, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1  -1//1   1//1  -1//1
  1//1   1//1   1//1   1//1
 -1//1   1//1   1//1   1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1
  1//1   1//1   1//1  -1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 12931 of type 3 
 
Rational{Int64}[1//1, 0//1, 1//1, 1//2, 1//2, -1//1, 0//1, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1  -1//1   1//1
  1//1  -1//1  -1//1  -1//1
 -1//1  -1//1  -1//1  -1//1
  1//1   1//1  -1//1  -1//1
 -1//1   1//1   1//1   1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1  -1//1
 -1//1   1//1  -1//1   1//1
 -1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1
  1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, 1//1, -1//1, 1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 6065 of type 5 
 
Rational{Int64}[1//1, 1//2, -1//2, -1//1, 0//1, 1//2, -1//2, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2] 
 
__________________ 
 
______________________________________________________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1
  1//1  -1//1  -1//1  -1//1
  1//1   1//1  -1//1  -1//1
 -1//1  -1//1  -1//1  -1//1
 -1//1   1//1   1//1   1//1
  1//1   1//1  -1//1   1//1
  1//1   1//1   1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1  -1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 3013 of type 5 
 
Rational{Int64}[1//1, -1//2, -1//2, 0//1, -1//1, 1//2, 1//2, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2] 
 
__________________ 
 
Using deterministic vertices: 
 


16×4 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1
  1//1   1//1   1//1  -1//1
 -1//1   1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1
  1//1   1//1   1//1   1//1
  1//1  -1//1  -1//1  -1//1
 -1//1  -1//1   1//1  -1//1
  1//1   1//1   1//1  -1//1
  1//1  -1//1  -1//1   1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1
  1//1  -1//1   1//1  -1//1
 -1//1  -1//1   1//1   1//1
 -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1  -1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1]

and convex mixture 
 


4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

 
 
we obtain vertex 12707 of type 5 
 
Rational{Int64}[1//1, 1//2, 1//2, 0//1, 1//1, -1//2, -1//2, 1//2, 0//1, 0//1, 1//2, -1//1, 0//1, 0//1, -1//2, 1//2] 
 
__________________ 
 
______________________________________________________________ 
 
______________________________________________________________ 
 
Vertex u3 
 
Using deterministic vertices: 
 


16×6 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1   1//1   1//1
 -1//1  -1//1   1//1  -1//1  -1//1   1//1
  1//1  -1//1  -1//1  -1//1  -1//1  -1//1
  1//1   1//1   1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1  -1//1  -1//1  -1//1
 -1//1   1//1   1//1   1//1  -1//1   1//1
  1//1   1//1   1//1  -1//1   1//1   1//1
  1//1   1//1   1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1  -1//1   1//1
 -1//1   1//1  -1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1   1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1  -1//1  -1//1
 -1//1   1//1   1//1  -1//1  -1//1   1//1
  1//1   1//1   1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1, 1//1, 1//1]

and convex mixture 
 


6-element Vector{Rational{Int64}}:
 1//6
 1//6
 1//6
 1//6
 1//6
 1//6

 
 
we obtain vertex 14485 of type 7 
 
Rational{Int64}[1//1, -1//3, -2//3, 2//3, -2//3, 1//3, 2//3, 2//3, 1//3, 0//1, 1//3, -2//3, -1//3, -1//3, 0//1, 1//1] 
 
__________________ 
 
Using deterministic vertices: 
 


16×6 Matrix{Rational{Int64}}:
  1//1   1//1   1//1   1//1   1//1   1//1
  1//1   1//1  -1//1   1//1   1//1  -1//1
 -1//1   1//1   1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1   1//1  -1//1  -1//1
  1//1   1//1  -1//1   1//1   1//1   1//1
  1//1  -1//1  -1//1  -1//1   1//1  -1//1
 -1//1  -1//1  -1//1   1//1  -1//1  -1//1
  1//1   1//1   1//1   1//1   1//1  -1//1
  1//1  -1//1   1//1  -1//1   1//1   1//1
 -1//1  -1//1   1//1   1//1  -1//1   1//1
 -1//1   1//1  -1//1   1//1   1//1   1//1
 -1//1  -1//1  -1//1  -1//1   1//1  -1//1
  1//1  -1//1  -1//1   1//1  -1//1  -1//1
 -1//1  -1//1   1//1   1//1  -1//1  -1//1
 -1//1   1//1   1//1  -1//1  -1//1   1//1
  1//1   1//1   1//1   1//1   1//1   1//1

'beta' values: Rational{Int64}[-1//1, -1//1, -1//1, -1//1, 1//1, 1//1]

and convex mixture 
 


6-element Vector{Rational{Int64}}:
 1//6
 1//6
 1//6
 1//6
 1//6
 1//6

 
 
we obtain vertex 11606 of type 7 
 
Rational{Int64}[1//1, 1//3, 2//3, -2//3, 2//3, -1//3, -2//3, 2//3, 1//3, 0//1, 1//3, -2//3, -1//3, -1//3, 0//1, 1//1] 
 
__________________ 
 
______________________________________________________________ 
 
