In [75]:
# initialize project:
using Pkg; Pkg.activate("./env");;

# Find current path
CURRENT = pwd(); LIB_PATH = joinpath(CURRENT,"lib");

# include auxilliary functions:
for file in readdir(LIB_PATH); include(joinpath(LIB_PATH,file)); end;

  Activating project at `~/GitHub/ClassicalLambda/env`


# Introduction and background:
Following the notation and convention of [arXiv:2312.10734](https://arxiv.org/abs/2312.10734), we can model a system of $n$-qubits by a Hilbert space $\mathcal{H} = (\mathbb{C}^2)^{\otimes n}$. Hermitian operators $\text{Herm}(\mathcal{H})$ form a real vector space with Hilbert-Schmidt inner product $\langle A,B \rangle = \text{Tr}(AB)$ for $A,B\in\text{Herm}(\mathcal{H})$.

## Stabilizer polytopes and $\Lambda$ polytopes

The single-qubit Pauli operators are given by

$$X = \begin{bmatrix} 0 &  1\\ 1 &  0\end{bmatrix},\quad%
  Y = \begin{bmatrix} 0 & -i\\ i &  0\end{bmatrix},\quad%
  Z = \begin{bmatrix} 1 &  0\\ 0 &  -1\end{bmatrix}.$$

  For $n$-qubits a Hermitian matrix $T$ is called a Pauli operator if it is of the form

  $$T = A_1\otimes\cdots\otimes A_n\quad\text{where}\quad A_i\in \{I,X,Y,Z\}.$$


The set of all Pauli operators form an orthogonal basis for the space of Hermitian matrices so that for any Hermitian matrix $A$ we have

$$A = \frac{1}{2^n} \sum_{T}\alpha_T T~,$$

where the $\alpha_T\in\mathbb{R}$ can be interpreted as the expectation value of the Pauli observable $T$ via the Born rule:

$$\langle A,T \rangle = \text{Tr}(AT) = \alpha_T~.$$

Thus any $A\in\text{Herm}(\mathcal{H})$ can be fully characterized by a vector $\alpha \in\mathbb{R}^{4^n}$ whose components are $\alpha_T$. For Hermitian matrices with $\text{Tr}(A) = 1$ this sets $\alpha_I = 1$ and we can work concretely in a real Euclidean space $\mathbb{R}^{4^n-1}$.

The $n$-qubit Pauli group $P_n$ consists of all Pauli operators $i^\zeta T$ where $\zeta \in \mathbb{Z}_4$. The $n$-qubit Clifford group is defined as $\text{Cl}_n = P_n/\left \langle e^{i\theta}I~:~\theta\in \mathbb{R}\right\rangle$. A stabilizer group $S\subset P_n$ is an abelian subgroup of the Pauli group in which all elements square to the identity. We call a stabilizer group maximal if the number of independent Pauli elements is $n$. Here we deal only with maximal stabilizer groups. By definition, for each stabilizer group there exists some $\left | \psi_S\right \rangle\in \mathcal{H}$ such that $s\left | \psi_S\right \rangle = \left | \psi_S\right \rangle$ for all $s\in S$.

The projector $\Pi_S$ onto the mutual $+1$ eigenspace of each $s\in S$ is given by:

$$\Pi_S = \frac{1}{2^n}\sum_{s\in S} s~.$$

Let $\mathcal{S}_n$ be the set of $n$-qubit stabilizer groups. The stabilizer polytope $\text{SP}_n$ is defined as the convex hull of stabilizer states. Its polar dual $\Lambda_n := \text{SP}_n^\ast$ can be formally defined as

$$\Lambda_n := \left \{ A\in \text{Herm}(\mathcal{H})~:~\text{Tr}(A) = 1,~\text{Tr}(\Pi_SA)\geq 0~\forall S\in \mathcal{S}_n \right\}~.$$

## ${2}$-qubits

Consider the $2$-qubit case. We call a Pauli operator *local* if it is of the form $A\otimes I$ or $I\otimes A$, where $A\in \{X,Y,Z\}$ is a single qubit Pauli matrix; otherwise we call it *nonlocal*. Let us organize our Pauli coordinates into local-nonlocal parts, such that $\alpha = ({\alpha}^\ell,{\alpha}^{n\ell})\in \mathbb{R}^{15}$, where:

$${\alpha}^\ell = \left(\alpha_{XI},\alpha_{YI},\alpha_{ZI},\alpha_{IX},\alpha_{IY},\alpha_{IZ} \right)\in \mathbb{R}^6$$
$${\alpha}^{n\ell} = \left(\alpha_{XX},\alpha_{XY},\alpha_{XZ},\alpha_{YX},\alpha_{YY},\alpha_{YZ},\alpha_{ZX},\alpha_{ZY},\alpha_{ZZ} \right)\in\mathbb{R}^9.$$

**Convention**: we index our coordinates by $1,\cdots,6$ for the local part while $a = 7,\cdots,15$ the nonlocal coordinates. (If the homogenizing coordinate $\alpha_I = 1$ is included then this offset by one so that the local coordinates have index $2,\cdots,7$, while the nonlocal coordinates have index $8,\cdots,16$.)

For $2$-qubits there are (up to signs) $15$ stabilizer groups. If a stabilizer group contains a local Pauli then it is called local; otherwise it is called nonlocal. There are $9$ local stabilizer groups and $6$ nonlocal ones. Disregarding the signs of the Pauli operators, the stabilizer groups consist of the Pauli operators:

\begin{align}
{\textbf{Local}:}\quad\quad & \{I,XI,IX,XX\}, \{I,XI,IY,XY\}, \{I,XI,IZ,XZ\},\notag\\
                                 & \{I,YI,IX,YX\}, \{I,YI,IY,YY\}, \{I,YI,IZ,YZ\},\notag\\
                                 & \{I,ZI,IX,ZX\}, \{I,ZI,IY,ZY\}, \{I,ZI,IZ,ZZ\},\notag\\
{\textbf{Nonlocal}:}\quad\quad & \{I,XY,YX,ZZ\}, \{I,YZ,ZY,XX\}, \{I,ZX,XZ,YY\},\notag\\
                                 & \{I,XY,ZX,YZ\}, \{I,YX,XZ,ZY\}, \{I,ZZ,YY,XX\}.\notag
\end{align}

In all but the last row, this products of Pauli operators multiplies to the $I$ whereas for the last row they multiply to $-I$.  For instance, we have

$$I\cdot XY \cdot YZ \cdot ZZ = I\quad \text{while} \quad I\cdot XX \cdot ZZ \cdot YY = - I~.$$

More generally, for commuting Pauli operators $A,B,AB$ their product satisfies $A\cdot B\cdot AB = (-1)^{\beta(A,B)} I$, where $\beta(A,B)\in \mathbb{Z}_2$. The function $\beta(A,B)$ can, in fact, be given a topological interpretation (see e.g., [arXiv:1701.01888](https://arxiv.org/abs/1701.01888)) and is the source of state-independent contextuality with qubits.



## ${2}$-qubit $\Lambda$ polytopes

Given a Hermitian $A\in \text{Herm}(\mathcal{H})$ with unit trace together with a stabilizer state $\Pi_S$ where $S=\{I,(-1)^a A,(-1)^b B,(-1)^{a+b+\beta(A,B)} AB\}$ ($a,b \in \mathbb{Z}_2$) we can define via the Born rule an inequality:

$$\text{Tr}(A\Pi_S) =  1+(-1)^a\alpha_A+(-1)^b\alpha_B+(-1)^{a+b+\beta(A,B)}\alpha_A \geq 0.$$

This is just the same as

$$(-1)^a\alpha_A+(-1)^b\alpha_B+(-1)^{a+b+\beta(A,B)}\alpha_A \geq -1~.$$

We can encode this system of linear inequalities into a matrix form $M\alpha \geq -\mathbb{1}_{60}$, where $\mathbb{1}_{60}$ is a vector of all ones and $M\in \mathbb{R}^{60\times 15}$ is a matrix whose components are

$$M_{S,T} = \text{Tr}(\Pi_S T).$$

We then have that $\Lambda_2$ can be defined as

$$\Lambda_2 := \left \{ \alpha \in \mathbb{R}^{15}~:~M\alpha\geq -\mathbb{1}_{60}\right \}.$$

We have $9$ stabilizer groups that are local and $6$ stabilizer groups that are nonlocal. We thus have $36$ local stabilizer states and $24$ nonlocal stabilizer states. Let $M^\ell$ and $M^{n\ell}$ be a submatrix of $M$ corresponding to those local and nonlocal stabilizer states, respectively. We thus define the local and nonlocal $\Lambda$-polytopes as
\begin{align}
\Lambda_2^\ell &:= \left \{ \alpha \in \mathbb{R}^{15}~:~M^{\ell}\alpha\geq -\mathbb{1}_{36}\right \},\\
\Lambda_2^{n\ell} &:= \left \{ \alpha \in \mathbb{R}^{15}~:~M^{n\ell}\alpha\geq -\mathbb{1}_{24}\right \}.
\end{align}

# Topological picture of stabilizer groups

Here we construct the matrix $M$ as well as $M^\ell$ and $M^{n\ell}$. We use the convention described in [twodim.jl](./lib/twodim.jl). In particular, each set of commuting Pauli observables $\{A,B,AB\}$ is associated with a triangle whose faces (or edges) are $A,B,AB$. Two triangles are glued along a common edge if they share a common Pauli observable

#### Pauli observables (edges)

Each distinct Pauli operator $T$ is given an identifying index and assigned a topological space, an edge or $1$-simplex. For completeness we must also specify the faces of the edge (its vertices or $0$-simplices). (In fact, without loss of generality, all vertices can be identified to a point.) 

As mentioned above, we use the ordering convention: $XI,YI,ZI,IX,IX,IZ,XX,XY,XZ,...,ZY,ZZ$ which corresponds to $1,2,\cdots,15$.

In [2]:
# Vertices:
X0 = [1];
# Edges:
X1 = [[i,[1,1]] for i in 1:15];

#### Stabilizer groups (triangles)

We associate an index $i = 1,\cdots,15$ with each of the maximal commuting sets of Pauli observables. To each index we assign a topological space (a triangle) for which we specify its faces (i.e., the edges or Pauli observables appearing in that set).

In [3]:
# Generate arrays corresponding to local stabilizer groups:
X2loc = [[1,[1,4,7]],[2,[1,5,8]],[3,[1,6,9]],
[4,[2,4,10]],[5,[2,5,11]],[6,[2,6,12]],
[7,[3,4,13]],[8,[3,5,14]],[9,[3,6,15]]];

# Generate arrays corresponding to local stabilizer groups:                   
X2nloc = [[10,[8,10,15]],[11,[12,14,7]],[12,[13,9,11]],
[13,[8,13,12]],[14,[10,9,14]],[15,[15,11,7]]];

# All 2-qubit stabilizer groups (triangles):
X2 = vcat(X2loc,X2nloc);

# Two-dimensional simplicial set:
X = [X0,X1,X2];

In [4]:
# Some sets have the property that multiplying all the Pauli operators A*B*AB = -I:
T = [[13,1,2],[14,1,2],[15,1,2]];

In [5]:
# Generate representation matrix M:
M = spaces_to_inequalities(X,T)

60×16 Matrix{Int64}:
 1   1  0  0   1   0   0   1   0   0   0   0   0   0   0   0
 1  -1  0  0  -1   0   0   1   0   0   0   0   0   0   0   0
 1   1  0  0  -1   0   0  -1   0   0   0   0   0   0   0   0
 1  -1  0  0   1   0   0  -1   0   0   0   0   0   0   0   0
 1   1  0  0   0   1   0   0   1   0   0   0   0   0   0   0
 1  -1  0  0   0  -1   0   0   1   0   0   0   0   0   0   0
 1   1  0  0   0  -1   0   0  -1   0   0   0   0   0   0   0
 1  -1  0  0   0   1   0   0  -1   0   0   0   0   0   0   0
 1   1  0  0   0   0   1   0   0   1   0   0   0   0   0   0
 1  -1  0  0   0   0  -1   0   0   1   0   0   0   0   0   0
 ⋮                 ⋮                   ⋮                   ⋮
 1   0  0  0   0   0   0   0  -1   0   0   0  -1  -1   0   0
 1   0  0  0   0   0   0   0   0  -1   1   0   0   0   1   0
 1   0  0  0   0   0   0   0   0   1  -1   0   0   0   1   0
 1   0  0  0   0   0   0   0   0   1   1   0   0   0  -1   0
 1   0  0  0   0   0   0   0   0  -1  -1   0   0   0  -1   0
 1 

## Vertices of $\Lambda_2$

There are $22320$ vertices of $\Lambda_2$ that fall into $8$ orbits ($T_1,\cdots,T_8$) under the action of $\text{Cl}_2$, the $2$-qubit Clifford group. 

In [6]:
# Generate Polymake object:
L2 = pm.polytope.Polytope(INEQUALITIES = M);

In [7]:
# Compute combinatorial symmetries, add property to pm object:
Aut = vertex_action_GAP(L2);

In [8]:
# Calculate Representative vertices (In convenient order)
L2rep = representative_vertices(L2,true)[[3,1,4,8,6,2,5,7],:]

pm::Matrix<pm::Rational>
1 -1 0 -1 0 0 0 0 0 0 1 1 -1 0 0 0
1 -1 -1 -1 1 0 0 -1 0 0 -1 0 0 -1 0 0
1 -1 1/2 0 0 1 -1/2 0 -1 1/2 -1/2 1/2 0 0 0 1/2
1 -1/2 -1/2 -1/2 1/2 0 0 0 -1/2 1/2 0 1/2 1/2 0 -1/2 -1/2
1 -1/2 0 -1/2 0 0 0 -1/2 -1/2 -1/2 -1 0 1 1/2 -1/2 1/2
1 -1 0 -1/2 1/2 1/2 1/2 -1/2 -1/2 -1/2 -1/2 1/2 1/2 0 -1 0
1 -2/3 -1/3 0 2/3 1/3 0 -1 -2/3 -1/3 -2/3 1/3 2/3 1/3 -2/3 1/3
1 1/2 -1/2 3/4 1/4 -3/4 -3/4 -1/4 -3/4 -1/4 1/4 1/4 3/4 1/2 -1/2 -1/2


In [9]:
# Calculate orbits:
L2orb = (vertex_orbit(Aut,L2,L2rep));

In [12]:
# local
Mloc = M[1:36,:]; display(Mloc)
# nonlocal
Mnloc = M[37:60,:]; display(Mnloc)

36×16 Matrix{Int64}:
 1   1  0   0   1   0   0   1   0  0  0  0  0   0   0   0
 1  -1  0   0  -1   0   0   1   0  0  0  0  0   0   0   0
 1   1  0   0  -1   0   0  -1   0  0  0  0  0   0   0   0
 1  -1  0   0   1   0   0  -1   0  0  0  0  0   0   0   0
 1   1  0   0   0   1   0   0   1  0  0  0  0   0   0   0
 1  -1  0   0   0  -1   0   0   1  0  0  0  0   0   0   0
 1   1  0   0   0  -1   0   0  -1  0  0  0  0   0   0   0
 1  -1  0   0   0   1   0   0  -1  0  0  0  0   0   0   0
 1   1  0   0   0   0   1   0   0  1  0  0  0   0   0   0
 1  -1  0   0   0   0  -1   0   0  1  0  0  0   0   0   0
 ⋮                  ⋮                 ⋮                 ⋮
 1   0  0  -1   1   0   0   0   0  0  0  0  0  -1   0   0
 1   0  0   1   0   1   0   0   0  0  0  0  0   0   1   0
 1   0  0  -1   0  -1   0   0   0  0  0  0  0   0   1   0
 1   0  0   1   0  -1   0   0   0  0  0  0  0   0  -1   0
 1   0  0  -1   0   1   0   0   0  0  0  0  0   0  -1   0
 1   0  0   1   0   0   1   0   0  0  0  0  0   0  

24×16 Matrix{Int64}:
 1  0  0  0  0  0  0   0   1   0   1   0   0   0   0   1
 1  0  0  0  0  0  0   0  -1   0  -1   0   0   0   0   1
 1  0  0  0  0  0  0   0   1   0  -1   0   0   0   0  -1
 1  0  0  0  0  0  0   0  -1   0   1   0   0   0   0  -1
 1  0  0  0  0  0  0   1   0   0   0   0   1   0   1   0
 1  0  0  0  0  0  0   1   0   0   0   0  -1   0  -1   0
 1  0  0  0  0  0  0  -1   0   0   0   0   1   0  -1   0
 1  0  0  0  0  0  0  -1   0   0   0   0  -1   0   1   0
 1  0  0  0  0  0  0   0   0   1   0   1   0   1   0   0
 1  0  0  0  0  0  0   0   0  -1   0   1   0  -1   0   0
 ⋮              ⋮                  ⋮                   ⋮
 1  0  0  0  0  0  0   0  -1   0   0   0  -1  -1   0   0
 1  0  0  0  0  0  0   0   0  -1   1   0   0   0   1   0
 1  0  0  0  0  0  0   0   0   1  -1   0   0   0   1   0
 1  0  0  0  0  0  0   0   0   1   1   0   0   0  -1   0
 1  0  0  0  0  0  0   0   0  -1  -1   0   0   0  -1   0
 1  0  0  0  0  0  0   1   0   0   0  -1   0   0   0   1
 1  0  0  

In [13]:
# projection to nonlocal coordinates:
_pi = [1,8,9,10,11,12,13,14,15,16];

## $\text{MP}$: Mermin polytope

The polytope $\text{MP}$ studied in [arXiv:2210.10186](https://arxiv.org/abs/2210.10186) is the projection of $\Lambda_2^{n\ell}$ to the nonlocal coordinates, i.e. $\text{MP} = \pi(\Lambda_2^{n\ell})$ where $\pi:\mathbb{R}^{15}\to\mathbb{R}^9$ is such that $\alpha\mapsto\alpha^{n\ell}$. There are two orbits, denoted $\bar T_1$ ($\times 48$) and $\bar T_2$ vertices ($\times 72$).

In [14]:
# Mnloc matrix taking only columns with nonlocal Pauli operators:
_Mnloc = Mnloc[:,_pi]; display(_Mnloc)
# MP as intersection of half-space inequalities defined by Mnloc_b:
MP = pm.polytope.Polytope(INEQUALITIES = _Mnloc);
# Facets:
H1 = Matrix{Rational{Int64}}(MP.FACETS);
# Vertices:
V1 = Matrix{Rational{Int64}}(MP.VERTICES);

24×10 Matrix{Int64}:
 1   0   1   0   1   0   0   0   0   1
 1   0  -1   0  -1   0   0   0   0   1
 1   0   1   0  -1   0   0   0   0  -1
 1   0  -1   0   1   0   0   0   0  -1
 1   1   0   0   0   0   1   0   1   0
 1   1   0   0   0   0  -1   0  -1   0
 1  -1   0   0   0   0   1   0  -1   0
 1  -1   0   0   0   0  -1   0   1   0
 1   0   0   1   0   1   0   1   0   0
 1   0   0  -1   0   1   0  -1   0   0
 ⋮                   ⋮              
 1   0  -1   0   0   0  -1  -1   0   0
 1   0   0  -1   1   0   0   0   1   0
 1   0   0   1  -1   0   0   0   1   0
 1   0   0   1   1   0   0   0  -1   0
 1   0   0  -1  -1   0   0   0  -1   0
 1   1   0   0   0  -1   0   0   0   1
 1   1   0   0   0   1   0   0   0  -1
 1  -1   0   0   0   1   0   0   0   1
 1  -1   0   0   0  -1   0   0   0  -1

In [16]:
# Compute Aut(MP):
G = vertex_action_GAP(MP);
# Obtain representative vertices:
MPrep = representative_vertices(MP,true)

pm::Matrix<pm::Rational>
1 -1 1 0 0 0 1 -1 -1 0
1 -1 -1 1 0 0 0 0 0 0


In [17]:
# Orbits of MP facets:
v1 = vertex_orbit(G,MP,MPrep);
# T2 vertices:
V1_prime = V1[v1[1],:]

72×10 Matrix{Rational{Int64}}:
 1  -1   1   0   0   0   1  -1  -1   0
 1  -1   0  -1   1   0  -1   0   1   0
 1   1   0   0   0  -1  -1   0  -1   1
 1  -1   0   1   1   0   1   0  -1   0
 1   0   1  -1   0  -1  -1   1   0   0
 1  -1   0   1  -1   0  -1   0   1   0
 1   0   1   0  -1   0   1  -1   0  -1
 1   0   1   1   1   0   0   0  -1   1
 1  -1   1   0   0   0  -1   1   1   0
 1   0   0   1   1  -1   0  -1  -1   0
 ⋮                   ⋮              
 1  -1   1   0  -1  -1   0   0   0  -1
 1  -1   0   1   0  -1   0  -1   0  -1
 1   1   0  -1   0  -1   0   1   0   1
 1  -1   0   0   0  -1   1   0  -1  -1
 1   0   1  -1   0   1   1  -1   0   0
 1   0   0   1   1   1   0   1  -1   0
 1   1   0   1   0   1   0   1   0  -1
 1  -1   0  -1   0  -1   0   1   0  -1
 1  -1  -1   0   1  -1   0   0   0  -1

# Classical polytopes

The polytope $\Lambda_2^\ell$ is isomorphic to $\text{NS}$, the nonsignaling polytope corresponding to the bipartite $(2,3,2)$ Bell scenario. A subset $D$ of the vertices of $\text{NS}$ are the so-called deterministic vertices. The convex hull of deterministic vertices is a subpolytope of $\text{NS}$ that we denote $\text{CL}$.

In [18]:
# Define simplicial set consisting only of local stabilizer groups:
Xloc = [X0,X1,X2loc];

# Generate deterministic vertices of scenario:
D = deterministic_vertices(Xloc)

64×16 Matrix{Int64}:
 1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
 1   1   1   1   1   1  -1   1   1  -1   1   1  -1   1   1  -1
 1   1   1   1   1  -1   1   1  -1   1   1  -1   1   1  -1   1
 1   1   1   1   1  -1  -1   1  -1  -1   1  -1  -1   1  -1  -1
 1   1   1   1  -1   1   1  -1   1   1  -1   1   1  -1   1   1
 1   1   1   1  -1   1  -1  -1   1  -1  -1   1  -1  -1   1  -1
 1   1   1   1  -1  -1   1  -1  -1   1  -1  -1   1  -1  -1   1
 1   1   1   1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
 1   1   1  -1   1   1   1   1   1   1   1   1   1  -1  -1  -1
 1   1   1  -1   1   1  -1   1   1  -1   1   1  -1  -1  -1   1
 ⋮                   ⋮                   ⋮                   ⋮
 1  -1  -1   1  -1  -1  -1   1   1   1   1   1   1  -1  -1  -1
 1  -1  -1  -1   1   1   1  -1  -1  -1  -1  -1  -1  -1  -1  -1
 1  -1  -1  -1   1   1  -1  -1  -1   1  -1  -1   1  -1  -1   1
 1  -1  -1  -1   1  -1   1  -1   1  -1  -1   1  -1  -1   1  -1
 1  -1  -1  -1   1  -1  -1  -1   1

## $\overline{CL}$: Projected classical polytope

We define the projected classical polytope $\overline{\text{CL}} := \pi(\text{CL})$. Following Howard and Vala [arXiv:1112.1516](https://arxiv.org/abs/1112.1516) we know that, aside from certain trivial non-negativity inequalities, that there are $72$ Clauser-Horne-Shimony-Holt (CHSH) facets of $\overline{\text{CL}}$.

In [19]:
# Projection of CL:
_D = D[:,_pi];
_CL = pm.polytope.Polytope(POINTS = _D);
# Facets:
H2 = Matrix{Rational{Int64}}(_CL.FACETS);
# Vertices:
V2 = Matrix{Rational{Int64}}(_CL.VERTICES);

#### Symmetries
The symmetry group of $\text{MP}$ and $\overline{\text{CL}}$ are the same. As we will see, one way to see that they should (at least) be related is that we have a bijective correspondence between $\bar T_2$ vertices and CHSH facets.

In [22]:
# Compute symmetry group of _CL
G = facets_action_GAP(_CL);
# Compute representative facets
_CLrep = representative_facets(_CL,true)

pm::Matrix<pm::Rational>
2 0 -1 -1 0 -1 1 0 0 0
1 -1 0 0 0 0 0 0 0 0


In [23]:
# Orbits of CLb facets:
h2 = facets_orbit(G,_CL,_CLrep);
# CHSH facets:
H2_prime = H2[h2[1],:]; display(H2_prime)

72×10 Matrix{Rational{Int64}}:
 2   0  -1  -1   0  -1   1   0   0   0
 2   0  -1  -1   0   0   0   0  -1   1
 2   1   0  -1   1   0   1   0   0   0
 2   0   0   0   0  -1   1   0  -1  -1
 2  -1   0  -1  -1   0   1   0   0   0
 2   1   0  -1   0   0   0   1   0   1
 2  -1  -1   0   1  -1   0   0   0   0
 2   0   0   0   0  -1  -1   0  -1   1
 2   0  -1  -1   0   0   0   0   1  -1
 2  -1   0  -1   0   0   0  -1   0   1
 ⋮                   ⋮              
 2  -1   1   0   0   0   0   1   1   0
 2   1   1   0  -1   1   0   0   0   0
 2  -1   0   1  -1   0  -1   0   0   0
 2   0   0   0   0   1  -1   0   1   1
 2   0  -1   1   0   1   1   0   0   0
 2  -1   1   0   1   1   0   0   0   0
 2   0   0   0  -1   1   0   1   1   0
 2   0   1   1   0   0   0   0   1  -1
 2   0   1   1   0   1  -1   0   0   0

## $\mathbf{\overline{\text{MP}}}$: "Classical" Mermin polytope

We define the "classical" part of the Mermin polytope as $\overline{\text{MP}} := \text{MP}\cap \overline{\text{CL}}$. In practice this means that $\overline{\text{MP}}$ is computed by intersecting the facets of $\overline{\text{CL}}$ together with those of $\text{MP}$. This gives the $H$-representation of $\overline{\text{MP}}$. We wish to convert to its $V$-representation. Luckily, if we have already computed the $V$-representation of either  $\text{MP}$ or $\overline{\text{CL}}$ then this simplifies the task of enumerating the vertices of $\overline{\text{MP}}$. Our main result is to show how the double description (DD) method helps to accomplish this.

In [24]:
# Define _MP:
H12 = vcat(H1,H2);
_MP = pm.polytope.Polytope(INEQUALITIES = H12);

In [25]:
# Combinatorial symmetries:
G = vertex_action_GAP(_MP);
# representative vertices of _MP:
_MPrep = representative_vertices(_MP,true)

pm::Matrix<pm::Rational>
1 -1 -1 -1 0 0 0 0 0 0
1 -1/2 -1 1/2 -1/2 0 -1/2 -1/2 0 1/2
1 0 -1 0 -1 0 0 0 0 1
1 -1/3 -2/3 -2/3 -2/3 1/3 -1/3 -2/3 -1/3 1/3
1 -2/3 2/3 0 2/3 0 2/3 -1/3 -1/3 1/3
1 -3/5 1/5 -3/5 -1/5 3/5 3/5 -3/5 -3/5 1/5
1 -1 0 1/3 1/3 2/3 -1/3 0 1/3 2/3
1 -1 1/3 0 -1/3 -1/3 -2/3 0 2/3 -1/3
1 -1 1/2 0 0 1/2 0 1/2 0 1/2
1 -1/2 0 -3/4 1/2 -1/2 -1/4 1/4 3/4 -1/2



# Overview: DD method:

The double description (DD) method is an incremental method for solving the vertex enumeration problem for convex polytopes, or more generally, the ray enumeration problem for polyhedral cones. The intuition behind the method can be pictured geometrically. Suppose we have an initial polyhedron $P$ (e.g., a cube) and a intersecting half-plane inequality. We distinguish between vertices (red) that violate the inequality, those that satisfy the inequality exactly (gray) and those lie on the other side (blue). New vertices are generated by taking convex combinations of red and blue vertices that are neighbors of one another; i.e., those that are connected by an edge. The red vertices are then discarded.


$\hspace{1 cm}$<img src="./graphics/rank-inc-a.png" width="200" height="200" /> $\hspace{1 cm}$ <img src="./graphics/rank-inc-b.png" width="200" height="200" /> $\hspace{1 cm}$<img src="./graphics/rank-inc-c.png" width="200" height="200" /> $\hspace{1 cm}$<img src="./graphics/rank-inc-d.png" width="200" height="200" />

Notice in the sequence shown above that initially no neighbors of the red vertices are blue. We simply discard the red vertices in this case. In the next iteration we insert another half-space inequality, but this time there are neighbors that are red and blue and thus there are newly generated vertices (pink).

## Our DD-based scheme:

Our key observation (one that also appears in [[Howard-Vala, 2011]](https://arxiv.org/abs/1112.1516)) is that each $\bar T_2$ vertex violates precisely one CHSH inequality $h_v$ such that

$$ h_v\cdot v = -2 < 0~,$$

while $\bar T_1$ vertices satisfy all CHSH inequalities. Moreover, the neighbors of each $\bar T_2$ vertex all lie precisely on the CHSH facet that it violates:

<figure>
<img src="./graphics/duality.png" style="display: block; margin: auto;" width="200" height="200" />
<figure>

Our scheme is as follows:

1. Identify a canonical $\bar T_2$ vertex $v$ and non-neighbors $w_i$ ($i=1,\cdots,4$),
2. For each $w_i$ insert a sequence of CHSH facets $h_j$ ($j=1,\cdots,k$) such that $h_{j} \cdot v = 0$,
3. This promotes non-neighbors ($w_i$) of $v$ to neighbors,
4. Insert the CHSH facet $h_v$ that $v$ violates,
4. Use the equation: $$u_i := pv+(1-p)w_i\quad \text{where}\quad p = \frac{1}{1-\frac{h_v\cdot v}{h_v\cdot w_i}}$$
    To obtain a point $u_i$ which is guaranteed by the DD method to be a vertex.

# Canonical vertex, neighbor, and ${2}$-neighbors

### Canonical vertex ${v}$ of $\mathbf{\text{MP}}$

In [26]:
v = Vector{Rational{Int64}}([1,1,1,0,1,-1,0,0,0,1]);

The canonical $\bar T_2$ vertex $v$ violates precisely one CHSH facet $h_v$ that is *dual* to it:

In [27]:
hv_idx = violated_inequality(v,H2); hv = H2[hv_idx,:]

1×10 Matrix{Rational{Int64}}:
 2  -1  -1  0  -1  1  0  0  0  0

### Canonical $\bar T_1$ neighbor ${v^\prime}$  of ${v}$ in ${\text{MP}}$

In [28]:
v_prime = Vector{Rational{Int64}}([1,1,0,0,0,-1,-1,0,-1,1]);

Joint rank of ${v}$ and ${v^\prime}$ in ${\text{MP}}$. Since $\text{dim}(\text{MP}) = 9$, if the joint rank is $9-1 = 8$, then the vertices are neighbors.

In [29]:
joint_rank(v,v_prime,H1)

8

Inner product with canonical facet $h_v$. All neighbors $v^\prime$ of $v$ have $h_v\cdot v^\prime = 0$. 

In [30]:
hv*v_prime

1-element Vector{Rational{Int64}}:
 0

### Canonical ${2}$-neighbors

We define the $2$-neighbor of a vertex $v$ to be the neighbor of a neighbor.  We identify four neighbors ${w_0}$, ${w_1}$, ${w_2}$, ${w_3}$ of $v^\prime$ in ${\text{MP}}$ that are not also neighbors of $v$.

In [31]:
w0 = Vector{Rational{Int64}}([1,1,-1,0,0,0,-1,-1,-1,0]);
w1 = Vector{Rational{Int64}}([1,1,-1,0,-1,-1,0,0,0,1]);
w2 = Vector{Rational{Int64}}([1,0,-1,0,0,-1,0,0,-1,0]);
w3 = Vector{Rational{Int64}}([1,0,-1,0,-1,0,-1,-1,0,1]);

In [32]:
W = Matrix([w0 w1 w2 w3])

10×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1   1   0   0
 -1  -1  -1  -1
  0   0   0   0
  0  -1   0  -1
  0  -1  -1   0
 -1   0   0  -1
 -1   0   0  -1
 -1   0  -1   0
  0   1   0   1

We can observe that these are, indeed, not neighbors of $v$. The joints ranks of $w_i$ ($i =0,\cdots,3$) with $v$ in ${\text{MP}}$ are:

In [33]:
for i in 1:4; println("Joint rank of v with w"*string(i)*" is: ", joint_rank(v,W[:,i],H1)); end;

Joint rank of v with w1 is: 7
Joint rank of v with w2 is: 6
Joint rank of v with w3 is: 6
Joint rank of v with w4 is: 6


Inner product with canonical facet $h_v$. All $2$-neighbors $w_i$ of $v$ have $h_v\cdot v^\prime > 0$. 

In [34]:
for i in 1:4; println("Inner product hv with w"*string(i)*" is: ", Int((hv*W[:,i])[1])); end;

Inner product hv with w1 is: 2
Inner product hv with w2 is: 2
Inner product hv with w3 is: 2
Inner product hv with w4 is: 4


# Generating vertices of $\mathbf{\overline{\text{MP}}}$

## Increasing joint rank

We look for common tight CHSH facets between $v$ and $w_i$.

In [35]:
# initialize empty Vector{Any}:
H2int = []; Zv = tight_inequalities(v,H2_prime);
for i in 1:4
    Zwi = tight_inequalities(W[:,i],H2_prime);
    Zint = collect(intersect(Set(Zv),Set(Zwi)));
    display(H2_prime[Zint,:])
    push!(H2int,H2_prime[Zint,:]);
end

4×10 Matrix{Rational{Int64}}:
 2  -1  0  -1  -1  0  1  0  0   0
 2  -1  0  -1   0  0  0  1  0  -1
 2   0  0   0   0  1  1  0  1  -1
 2   0  0   0  -1  1  0  1  1   0

4×10 Matrix{Rational{Int64}}:
 2  -1  0  -1  0  0   0   1   0  -1
 2   0  0   0  0  1   1   0   1  -1
 2   0  0   0  0  1  -1   0  -1  -1
 2  -1  0   1  0  0   0  -1   0  -1

2×10 Matrix{Rational{Int64}}:
 2  0  0  0  -1  1  0  1  1   0
 2  0  0  0   0  1  1  0  1  -1

2×10 Matrix{Rational{Int64}}:
 2  -1  0  -1  0  0  0  1  0  -1
 2   0  0   0  0  1  1  0  1  -1

Compute joint rank of $v$ and $w_i$ with facets of $\text{MP}$ together with CHSH facets of $\overline{\text{CL}}$.

In [36]:
Zv = tight_inequalities(v,H1);
for i in 1:4
    # find common tight inequalities in H1:
    Zwi = tight_inequalities(W[:,i],H1);
    Zint = collect(intersect(Set(Zv),Set(Zwi)));
    H1Z = H1[Zint,:];
    # Concatenate tight H1 and H2 inequalities:
    H12Z = vcat(H1Z,H2int[i]);
    println("Updated joint rank of v with w"*string(i)*" is: ", rank(H12Z))
end

Updated joint rank of v with w1 is: 8
Updated joint rank of v with w2 is: 8
Updated joint rank of v with w3 is: 8
Updated joint rank of v with w4 is: 8


## Generate vertices using DD method

### function: new_vertex

Given the cone $P_0^\ast$ of a full-dimensional polytope $P_0\subseteq \mathbb{R}^d$ and a hyperplane $h\cdot x = 0$, the DD method guarantees that for all pairs of adjacent extreme rays $v,v^\prime\in P_0^\ast$ (i.e., joint rank is $d-2$) such that $h\cdot v < 0$ and $h\cdot v^\prime > 0$ that the positive sum of these points given by

$$u = pv-(1-p)v^\prime\quad\text{where}\quad p = \frac{1}{1-\frac{h\cdot v}{h\cdot v^\prime}}\in [0,1]$$

is an extreme ray of the new cone $P_1^\ast$, which is obtained from $P^\ast_0$ by the insertion of the new inequality $h\cdot x \geq 0$.

**Input:** Vector: v_minus: violating vector ($d\times 1$)

**Input:** Vector: v_plus: satisfying vector ($d\times 1$)

**Input:** Vector: h: facet vector ($1\times d$)

**Output:** Vector: new_vertex ($d\times 1$)

In [37]:
function new_vertex(v_minus,v_plus,h)
    d = size(v_minus)[1];
    if size(h)[1] == d
        a = (transpose(h)*v_minus)[1];
        b = (transpose(h)*v_plus)[1];
    else
        a = ((h)*v_minus)[1];
        b = ((h)*v_plus)[1];
    end
    p = b/(b-a);
    if p < 0
        return "No vertex possible"
    elseif p == 0
        return "No new vertex possible"
    else
        return p*v_minus+(1-p)*v_plus
    end
end

new_vertex (generic function with 1 method)

In [38]:
U = zeros(Rational{Int64},10,4);
for i in 1:4; U[:,i] .= new_vertex(v,W[:,i],hv); end; U

10×4 Matrix{Rational{Int64}}:
   1     1    1      1
   1     1   1//2   2//3
   0     0    0     1//3
   0     0    0      0
  1//2   0   1//2   1//3
 -1//2  -1   -1    -2//3
 -1//2   0    0    -1//3
 -1//2   0    0    -1//3
 -1//2   0  -1//2    0
  1//2   1   1//2    1

# New vertices of $\Lambda_2$ 

We consider lifts of the vertices $u_{i}\in \overline{\text{MP}}$, by which we mean points $\tilde u_{i}\in \mathbb{R}^{15}$ satisfying $M^\ell \tilde u_{i}\geq I_{36\times 1}$ and mapping to $u_i$ under the projection $\pi:\mathbb{R}^{15}\to \mathbb{R}^{9}$.
The fact that $\overline{\text{MP}}$ is contained in $\overline{\text{CL}}$ allows for a simplified method of lifting that ensures that $\tilde u_{i} \in \Lambda_{2}\cap \text{CL}$ and, in particular, such ``classical" lifts yield vertices of $\Lambda_{2}$.


In [39]:
# local inequalities:
S = [i for i in 1:36];
# nonlocal coordinates
s = [i for i in 8:16];

### General lifting

For a given $u_i\in \overline{\text{MP}}$ the set of $\tilde u_i$ satisfying $M^\ell \tilde u_{i}\geq I_{36\times 1}$ itself forms a convex polytope that we denote $\widetilde{\text{MP}}_{u_i}$.

In [40]:
# Create array of vertices (Easier for searching)
L2array = polymake_to_array(L2.VERTICES,Rational{Int64});

We lift each $u_i$ and generate the projection of $\widetilde{\text{MP}}_{u_i}$ to its local coordinates, as the nonlocal coordinates are fixed by $u_i\in \mathbb{R}^9$.

In [49]:
# Lift each ui:
for i in 1:4
    # generate polytope of lifts:
    __MPi = lift_mp1(U[2:end,i],M,S,s);
    
    # display vertices:
    println("For vertex u"*string(i-1)*" the polytope of lifts has "*string(__MPi.N_VERTICES)*" total vertices. \n ")

    #println((representative_vertices(__MPi,false)));

    #println("_______________________________________________________ \n ")
    
    # run through all vertices of __MPi
    for j in 1:size(__MPi.VERTICES)[1]
        # vertex of MP_ui:
        v = Vector{Rational{Int64}}(__MPi.VERTICES[j,:])
        
        # compute local rank:
        Zloc = tight_inequalities(v,Mloc);
        rloc = rank(Mloc[Zloc,:]);
        
        # compute total rank:
        Z = tight_inequalities(v,M);
        r = rank(M[Z,:]);
        
        if r == 15
            v_idx = findall(y->y==v,L2array)[1];
            for t in 1:8
                if v_idx in L2orb[t]
                    println("One of those vertices is number "*string(v_idx)*" and type "*string(t)*" in Lambda2: ")
                    println(v, "\n ")
                    println("______________________\n")
                end
            end
        end
    end
    println("_______________________________________________________\n ")
end

For vertex u0 the polytope of lifts has 22 total vertices. 
 
One of those vertices is number 18344 and type 6 in Lambda2: 
Rational{Int64}[1, -1//2, 0, 1, -1//2, -1//2, 1//2, 1, 0, 0, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
______________________

One of those vertices is number 9729 and type 5 in Lambda2: 
Rational{Int64}[1, 0, 1//2, 1//2, 0, -1, 0, 1, 0, 0, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
______________________

One of those vertices is number 12183 and type 6 in Lambda2: 
Rational{Int64}[1, -1//2, -1, 0, -1//2, 1//2, 1//2, 1, 0, 0, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
______________________

One of those vertices is number 9561 and type 6 in Lambda2: 
Rational{Int64}[1, 1//2, 0, -1, 1//2, 1//2, -1//2, 1, 0, 0, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
______________________

One of those vertices is number 4845 and type 6 in Lambda2: 
Rational{Int64}[1, 1//2, 1, 0, 1//2, -1//2, -1//2, 1, 0, 0, 1//2, -1//2, -1//2, -1//2, -1//2, 1//2]
 
______________________

One of

## Classical lift

In [71]:
decomps = [];
for i in 1:4
    display("For vertex u"*string(i-1))
    
    # compute decomposition of ui in terms of V2:
    delta_i, cd_i = convex_decomposition(U[:,i],H2,V2);
    
    # collect results:
    push!(decomps,[delta_i,Matrix{Rational{Int64}}(cd_i.VERTICES)]);
    
    # print results:
    display("Vertices appearing in decomposition: ");
    display((delta_i));# println("\n ");
    display("Vertices of allowed convex combinations: ");
    display(decomps[i][2]);# println("\n ")
end

"For vertex u0"

"Vertices appearing in decomposition: "

10×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1   1   1   1
 -1   1  -1   1
  1  -1  -1   1
  1   1   1  -1
 -1   1  -1  -1
  1  -1  -1  -1
  1  -1  -1  -1
 -1  -1   1  -1
  1   1   1  -1

"Vertices of allowed convex combinations: "

1×5 Matrix{Rational{Int64}}:
 1  1//4  1//4  1//4  1//4

"For vertex u1"

"Vertices appearing in decomposition: "

10×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"Vertices of allowed convex combinations: "

1×5 Matrix{Rational{Int64}}:
 1  1//4  1//4  1//4  1//4

"For vertex u2"

"Vertices appearing in decomposition: "

10×8 Matrix{Rational{Int64}}:
  1   1   1   1   1   1   1   1
  1   1   1  -1   1   1  -1  -1
 -1  -1  -1   1   1   1   1   1
  1  -1  -1   1   1  -1   1  -1
  1   1   1   1  -1  -1   1   1
 -1  -1  -1  -1  -1  -1  -1  -1
  1  -1  -1  -1  -1   1  -1   1
  1   1  -1  -1  -1  -1   1   1
 -1  -1   1   1  -1  -1  -1  -1
  1  -1   1   1  -1   1  -1   1

"Vertices of allowed convex combinations: "

3×9 Matrix{Rational{Int64}}:
 1  1//4   0    1//4   0    1//4   0     0    1//4
 1  1//4   0    1//4   0     0    1//4  1//4   0
 1  1//4  1//4   0    1//4   0    1//4   0     0

"For vertex u3"

"Vertices appearing in decomposition: "

10×6 Matrix{Rational{Int64}}:
  1   1   1   1   1   1
  1   1   1   1  -1   1
 -1   1  -1   1   1   1
  1  -1  -1   1   1  -1
  1   1   1  -1   1  -1
 -1   1  -1  -1  -1  -1
  1  -1  -1  -1  -1   1
  1  -1  -1   1  -1  -1
 -1  -1   1   1   1  -1
  1   1   1   1   1   1

"Vertices of allowed convex combinations: "

1×7 Matrix{Rational{Int64}}:
 1  1//6  1//6  1//6  1//6  1//6  1//6

### Lift of $\mathbf{\overline{\text{MP}}}$ vertices

In [82]:
classical_vertices = [[ ] for i in 1:4];

# Lift each vertex ui of MPb:
for i in 1:4
    display("Vertex u"*string(i-1))
    preimages_array = [];
    
    # find preimages of Cb vertices:
    for j in 1:size(decomps[i][1])[2]
        
        # define vertex of Cb:
        delta = decomps[i][1][2:end,j];
        
        # find elements of D that project to delta
        preimage_idx = [k for k in 1:size(D)[1] if (D[k,8:16] == delta)]
        
        # create matrix of preimages:
        preimage = transpose(Matrix{Rational{Int64}}(D[preimage_idx,:]));
        push!(preimages_array,preimage);
    end
    
    
    # perform convex combinations:
    for k in 1:size(decomps[i][2])[1]
        vertices_in_decomposition = findall(y->y != 0,decomps[i][2][k,2:end])
        
        # number of combinations:
        bit_strings = all_dit_strings(2,length(vertices_in_decomposition));
        for x in bit_strings
            # preimages used:
            subset_of_preimages = preimages_array[vertices_in_decomposition]
            
            # initialize matrix of vertices in decomposition:
            R = subset_of_preimages[1][:,x[1]+1];
            for j in 2:length(subset_of_preimages)
                R = hcat(R,subset_of_preimages[j][:,(x[j]+1)])
            end
            
            # parameters of convex mixture
            mixture = (decomps[i][2][k,2:end])[vertices_in_decomposition]
            # classical distribution:
            v = R*mixture;
            # rank of distribution:
            Zv = tight_inequalities(v, M); rank_Mv = rank(M[Zv,:]);
            if rank_Mv == 15
                v_idx = findall(y->y == v,L2array)[1]
                for t in 1:8
                    if v_idx in L2orb[t]
                        pair = [v,t];
                        if (pair in classical_vertices[i]) == false
                            push!(classical_vertices[i],pair)
                            display("Using deterministic vertices:");
                            display(R)
                            display("and convex mixture")
                            display((mixture));
                            display("we obtain vertex "*string(v_idx)*" of type "*string(t))
                            display(v)
                            display("__________________")
                        end
                    end
                end
            end
        end
        display("______________________________________________________________ ")
    end
    
    # remove redundant vertices:
    classical_vertices[i] = collect(Set(classical_vertices[i]));
end

"Vertex u0"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1   1   1  -1
  1   1   1   1
  1  -1  -1   1
  1   1   1  -1
 -1   1  -1  -1
  1  -1  -1  -1
  1   1   1   1
 -1   1  -1   1
  1  -1  -1   1
  1   1   1  -1
 -1   1  -1  -1
  1  -1  -1  -1
  1  -1  -1  -1
 -1  -1   1  -1
  1   1   1  -1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 4845 of type 6"

16-element Vector{Rational{Int64}}:
   1
  1//2
   1
   0
  1//2
 -1//2
 -1//2
   1
   0
   0
  1//2
 -1//2
 -1//2
 -1//2
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1  -1   1  -1
  1  -1   1   1
  1   1  -1   1
  1  -1   1  -1
 -1  -1  -1  -1
  1   1  -1  -1
  1   1   1   1
 -1   1  -1   1
  1  -1  -1   1
  1   1   1  -1
 -1   1  -1  -1
  1  -1  -1  -1
  1  -1  -1  -1
 -1  -1   1  -1
  1   1   1  -1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 9729 of type 5"

16-element Vector{Rational{Int64}}:
   1
   0
  1//2
  1//2
   0
  -1
   0
   1
   0
   0
  1//2
 -1//2
 -1//2
 -1//2
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1  -1  -1  -1
  1  -1  -1   1
  1   1   1   1
  1  -1  -1  -1
 -1  -1   1  -1
  1   1   1  -1
  1   1   1   1
 -1   1  -1   1
  1  -1  -1   1
  1   1   1  -1
 -1   1  -1  -1
  1  -1  -1  -1
  1  -1  -1  -1
 -1  -1   1  -1
  1   1   1  -1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 18344 of type 6"

16-element Vector{Rational{Int64}}:
   1
 -1//2
   0
   1
 -1//2
 -1//2
  1//2
   1
   0
   0
  1//2
 -1//2
 -1//2
 -1//2
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1   1   1   1
 -1   1   1  -1
 -1  -1  -1  -1
 -1   1   1   1
  1   1  -1   1
 -1  -1  -1   1
  1   1   1   1
 -1   1  -1   1
  1  -1  -1   1
  1   1   1  -1
 -1   1  -1  -1
  1  -1  -1  -1
  1  -1  -1  -1
 -1  -1   1  -1
  1   1   1  -1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 9561 of type 6"

16-element Vector{Rational{Int64}}:
   1
  1//2
   0
  -1
  1//2
  1//2
 -1//2
   1
   0
   0
  1//2
 -1//2
 -1//2
 -1//2
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1   1  -1   1
 -1   1  -1  -1
 -1  -1   1  -1
 -1   1  -1   1
  1   1   1   1
 -1  -1   1   1
  1   1   1   1
 -1   1  -1   1
  1  -1  -1   1
  1   1   1  -1
 -1   1  -1  -1
  1  -1  -1  -1
  1  -1  -1  -1
 -1  -1   1  -1
  1   1   1  -1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 6124 of type 5"

16-element Vector{Rational{Int64}}:
   1
   0
 -1//2
 -1//2
   0
   1
   0
   1
   0
   0
  1//2
 -1//2
 -1//2
 -1//2
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1  -1  -1   1
 -1  -1  -1  -1
 -1   1   1  -1
 -1  -1  -1   1
  1  -1   1   1
 -1   1   1   1
  1   1   1   1
 -1   1  -1   1
  1  -1  -1   1
  1   1   1  -1
 -1   1  -1  -1
  1  -1  -1  -1
  1  -1  -1  -1
 -1  -1   1  -1
  1   1   1  -1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 12183 of type 6"

16-element Vector{Rational{Int64}}:
   1
 -1//2
  -1
   0
 -1//2
  1//2
  1//2
   1
   0
   0
  1//2
 -1//2
 -1//2
 -1//2
 -1//2
  1//2

"__________________"

"______________________________________________________________ "

"Vertex u1"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1   1   1  -1
  1   1  -1   1
  1  -1   1   1
  1   1   1  -1
 -1  -1   1  -1
  1  -1   1   1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 12722 of type 3"

16-element Vector{Rational{Int64}}:
   1
  1//2
  1//2
  1//2
  1//2
 -1//2
  1//2
   1
   0
   0
   0
  -1
   0
   0
   0
   1

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1   1  -1   1
  1   1   1  -1
  1  -1  -1  -1
  1   1  -1   1
 -1  -1  -1   1
  1  -1  -1  -1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 9815 of type 3"

16-element Vector{Rational{Int64}}:
   1
  1//2
  1//2
 -1//2
  1//2
 -1//2
 -1//2
   1
   0
   0
   0
  -1
   0
   0
   0
   1

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1  -1   1   1
  1  -1  -1  -1
  1   1   1  -1
  1  -1   1   1
 -1   1   1   1
  1   1   1  -1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 10671 of type 3"

16-element Vector{Rational{Int64}}:
   1
  1//2
 -1//2
  1//2
  1//2
  1//2
  1//2
   1
   0
   0
   0
  -1
   0
   0
   0
   1

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1  -1  -1  -1
  1  -1   1   1
  1   1  -1   1
  1  -1  -1  -1
 -1   1  -1  -1
  1   1  -1   1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 18350 of type 3"

16-element Vector{Rational{Int64}}:
   1
 -1//2
  1//2
  1//2
 -1//2
 -1//2
  1//2
   1
   0
   0
   0
  -1
   0
   0
   0
   1

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1   1   1   1
 -1   1  -1  -1
 -1  -1   1  -1
 -1   1   1   1
  1  -1   1   1
 -1  -1   1  -1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 15077 of type 3"

16-element Vector{Rational{Int64}}:
   1
  1//2
 -1//2
 -1//2
  1//2
  1//2
 -1//2
   1
   0
   0
   0
  -1
   0
   0
   0
   1

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1   1  -1  -1
 -1   1   1   1
 -1  -1  -1   1
 -1   1  -1  -1
  1  -1  -1  -1
 -1  -1  -1   1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 17985 of type 3"

16-element Vector{Rational{Int64}}:
   1
 -1//2
  1//2
 -1//2
 -1//2
 -1//2
 -1//2
   1
   0
   0
   0
  -1
   0
   0
   0
   1

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1  -1   1  -1
 -1  -1  -1   1
 -1   1   1   1
 -1  -1   1  -1
  1   1   1  -1
 -1   1   1   1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 15364 of type 3"

16-element Vector{Rational{Int64}}:
   1
 -1//2
 -1//2
  1//2
 -1//2
  1//2
  1//2
   1
   0
   0
   0
  -1
   0
   0
   0
   1

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1  -1  -1   1
 -1  -1   1  -1
 -1   1  -1  -1
 -1  -1  -1   1
  1   1  -1   1
 -1   1  -1  -1
  1   1   1   1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1  -1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1   1  -1
 -1   1   1  -1
  1   1   1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 16710 of type 3"

16-element Vector{Rational{Int64}}:
   1
 -1//2
 -1//2
 -1//2
 -1//2
  1//2
 -1//2
   1
   0
   0
   0
  -1
   0
   0
   0
   1

"__________________"

"______________________________________________________________ "

"Vertex u2"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1   1  -1  -1
  1   1   1   1
  1  -1   1   1
  1   1  -1   1
 -1  -1  -1  -1
  1  -1  -1   1
  1   1   1  -1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1   1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1  -1   1
 -1   1  -1  -1
  1   1  -1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 12931 of type 3"

16-element Vector{Rational{Int64}}:
   1
   0
   1
  1//2
  1//2
  -1
   0
  1//2
   0
   0
  1//2
  -1
   0
   0
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1  -1  -1  -1
  1  -1   1   1
  1   1   1   1
  1  -1  -1   1
 -1   1  -1  -1
  1   1  -1   1
  1   1   1  -1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1   1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1  -1   1
 -1   1  -1  -1
  1   1  -1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 18353 of type 5"

16-element Vector{Rational{Int64}}:
   1
 -1//2
  1//2
   1
   0
 -1//2
  1//2
  1//2
   0
   0
  1//2
  -1
   0
   0
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1   1   1   1
 -1   1  -1  -1
 -1  -1  -1  -1
 -1   1   1  -1
  1  -1   1   1
 -1  -1   1  -1
  1   1   1  -1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1   1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1  -1   1
 -1   1  -1  -1
  1   1  -1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 6065 of type 5"

16-element Vector{Rational{Int64}}:
   1
  1//2
 -1//2
  -1
   0
  1//2
 -1//2
  1//2
   0
   0
  1//2
  -1
   0
   0
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1  -1   1   1
 -1  -1  -1  -1
 -1   1  -1  -1
 -1  -1   1  -1
  1   1   1   1
 -1   1   1  -1
  1   1   1  -1
 -1  -1   1   1
  1  -1   1  -1
  1   1  -1   1
 -1  -1  -1  -1
  1  -1  -1   1
  1  -1  -1   1
 -1   1  -1  -1
  1   1  -1   1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 11897 of type 3"

16-element Vector{Rational{Int64}}:
   1
   0
  -1
 -1//2
 -1//2
   1
   0
  1//2
   0
   0
  1//2
  -1
   0
   0
 -1//2
  1//2

"__________________"

"______________________________________________________________ "

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
  1   1   1  -1
  1   1  -1   1
  1  -1  -1   1
  1   1   1   1
 -1  -1   1  -1
  1  -1  -1  -1
  1   1   1  -1
 -1  -1   1   1
  1  -1  -1   1
  1   1  -1   1
 -1  -1  -1  -1
  1  -1   1  -1
  1  -1  -1   1
 -1   1  -1  -1
  1   1   1  -1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 12707 of type 5"

16-element Vector{Rational{Int64}}:
   1
  1//2
  1//2
   0
   1
 -1//2
 -1//2
  1//2
   0
   0
  1//2
  -1
   0
   0
 -1//2
  1//2

"__________________"

"Using deterministic vertices:"

16×4 Matrix{Rational{Int64}}:
  1   1   1   1
 -1  -1  -1   1
 -1  -1   1  -1
 -1   1   1  -1
 -1  -1  -1  -1
  1   1  -1   1
 -1   1   1   1
  1   1   1  -1
 -1  -1   1   1
  1  -1  -1   1
  1   1  -1   1
 -1  -1  -1  -1
  1  -1   1  -1
  1  -1  -1   1
 -1   1  -1  -1
  1   1   1  -1

"and convex mixture"

4-element Vector{Rational{Int64}}:
 1//4
 1//4
 1//4
 1//4

"we obtain vertex 3013 of type 5"

16-element Vector{Rational{Int64}}:
   1
 -1//2
 -1//2
   0
  -1
  1//2
  1//2
  1//2
   0
   0
  1//2
  -1
   0
   0
 -1//2
  1//2

"__________________"

"______________________________________________________________ "

"______________________________________________________________ "

"Vertex u3"

"Using deterministic vertices:"

16×6 Matrix{Rational{Int64}}:
  1   1   1   1   1   1
  1   1   1  -1  -1   1
  1   1   1   1   1  -1
  1  -1  -1  -1  -1  -1
  1   1   1  -1   1   1
 -1   1  -1  -1  -1   1
  1  -1  -1  -1  -1  -1
  1   1   1   1  -1   1
 -1   1  -1   1   1   1
  1  -1  -1   1   1  -1
  1   1   1  -1   1  -1
 -1   1  -1  -1  -1  -1
  1  -1  -1  -1  -1   1
  1  -1  -1   1  -1  -1
 -1  -1   1   1   1  -1
  1   1   1   1   1   1

"and convex mixture"

6-element Vector{Rational{Int64}}:
 1//6
 1//6
 1//6
 1//6
 1//6
 1//6

"we obtain vertex 11606 of type 7"

16-element Vector{Rational{Int64}}:
   1
  1//3
  2//3
 -2//3
  2//3
 -1//3
 -2//3
  2//3
  1//3
   0
  1//3
 -2//3
 -1//3
 -1//3
   0
   1

"__________________"

"Using deterministic vertices:"

16×6 Matrix{Rational{Int64}}:
  1   1   1   1   1   1
 -1  -1  -1   1   1  -1
 -1  -1  -1  -1  -1   1
 -1   1   1   1   1   1
 -1  -1  -1   1  -1  -1
  1  -1   1   1   1  -1
 -1   1   1   1   1   1
  1   1   1   1  -1   1
 -1   1  -1   1   1   1
  1  -1  -1   1   1  -1
  1   1   1  -1   1  -1
 -1   1  -1  -1  -1  -1
  1  -1  -1  -1  -1   1
  1  -1  -1   1  -1  -1
 -1  -1   1   1   1  -1
  1   1   1   1   1   1

"and convex mixture"

6-element Vector{Rational{Int64}}:
 1//6
 1//6
 1//6
 1//6
 1//6
 1//6

"we obtain vertex 14485 of type 7"

16-element Vector{Rational{Int64}}:
   1
 -1//3
 -2//3
  2//3
 -2//3
  1//3
  2//3
  2//3
  1//3
   0
  1//3
 -2//3
 -1//3
 -1//3
   0
   1

"__________________"

"______________________________________________________________ "